# -*- coding: utf-8 -*-
"""Glosario oficial COLBASOFT — Fase 4. Fuente única de definiciones (glosario y lenguaje ubicuo).
T(término, definición oficial, definición prohibida, sinónimos prohibidos, contexto, origen, relaciones, ejemplo, ul)"""

TERMS = []
def T(term, d, prohib, sin, ctx, origen, rel, ej="", ul=False, v11=False, v12=False):
    """v11=True: término agregado en la v1.1; v12=True: agregado en la v1.2. Reciben un GL-nnn a continuación de los anteriores, sin renumerar."""
    TERMS.append(dict(term=term, d=d, prohib=prohib, sin=sin, ctx=ctx, origen=origen, rel=rel, ej=ej, ul=ul, v11=v11, v12=v12))

# ------------------------------------------------------------------ Catálogo e identidad
T("Prenda", "Artículo textil terminado o insumo textil que la empresa almacena. Es el objeto físico del que hablan las personas; el sistema no lo controla directamente sino a través de su Referencia y de sus unidades de inventario.",
  "No es la unidad que el sistema controla ni un registro del catálogo.", "", "Catálogo textil", "SPEC · CD-01 · Monografía §5, §7.1", "Referencia; Unidad de inventario", "Una camiseta azul talla M en un estante", True)
T("Referencia", "Identificador comercial de un modelo o artículo textil, independiente de talla, color y lote. Es la unidad de catálogo; se activa y desactiva, nunca se elimina.",
  "No es una prenda física, ni un SKU, ni un código de barras de proveedor.", "producto (designa a COLBASOFT, HD-01), modelo, estilo, artículo", "Catálogo textil", "SPEC · CD-02", "SKU; Categoría; Unidad de medida; Código de referencia", "CAM-001 · camiseta cuello redondo", True)
T("Talla", "Dimensión de variación de una referencia que expresa el tamaño; toma valores de un conjunto definido por la empresa.",
  "No es un atributo libre de texto ni una referencia distinta.", "", "Catálogo textil", "SPEC · CD-03", "SKU; Color", "M; 10; XL", True)
T("Color", "Dimensión de variación de una referencia que expresa el acabado cromático; toma valores de un conjunto definido por la empresa.",
  "No es un atributo libre de texto ni una referencia distinta.", "", "Catálogo textil", "SPEC · CD-04", "SKU; Talla", "Azul; Crudo", True)
T("SKU", "Combinación única e irrepetible de Referencia + Talla + Color. Unidad de control de catálogo con la que se planifica, se consulta y se fijan los umbrales mínimo y máximo. No tiene existencia propia: su existencia es la suma de sus unidades de inventario.",
  "No es la unidad que se cuenta y mueve (esa es la unidad de inventario) ni incluye el lote.", "variante (HD-01), ítem", "Catálogo textil", "SPEC · CD-05", "Referencia; Lote; Unidad de inventario; Umbral de existencia mínima", "CAM-001 · M · Azul", True)
T("Categoría", "Agrupación de referencias con propósito de organización, zona preferente y reporte. Una referencia pertenece a una sola categoría.",
  "No es una zona física ni un tipo de movimiento.", "familia, línea", "Catálogo textil", "SPEC · CD-10", "Referencia; Zona", "Camisetas", True)
T("Unidad de medida", "Magnitud en que se cuenta una referencia (unidades, metros, rollos, kilogramos). Es fija por referencia y no cambia si existen movimientos; el dominio no convierte entre unidades.",
  "No es la capacidad de una ubicación ni una conversión entre unidades.", "", "Catálogo textil", "SPEC · CD-11", "Referencia; Cantidad", "metros (tela en rollo)", True)
T("Código de referencia", "Identidad única de una referencia en todo el catálogo, activa o inactiva.", "No se reutiliza al desactivar la referencia.", "", "Catálogo textil", "SPEC · RN-002", "Referencia", "CAM-001")
T("Umbral de existencia mínima", "Existencia disponible por debajo de la cual un SKU dispara la alerta de ruptura de stock inminente.", "No es una meta de inventario ni una orden de reposición automática.", "punto de reorden", "Alertas y reglas", "SPEC · HU-013", "SKU; Ruptura de stock; Alerta", "Mínimo 30 unidades")
T("Umbral de existencia máxima", "Existencia por encima de la cual un SKU dispara la alerta de sobre stock.", "No es un límite físico que impida recibir mercancía.", "", "Alertas y reglas", "SPEC · HU-013", "SKU; Sobre stock; Alerta", "Máximo 400 unidades")
T("Catálogo", "Conjunto de referencias, SKU, categorías y unidades de medida que define qué puede existir en inventario.", "No es una lista de precios ni un catálogo comercial de venta `[DC-03]`.", "maestro de productos", "Catálogo textil", "SPEC · M-03", "Referencia; SKU; Categoría")
T("Carga masiva de catálogo", "Incorporación del catálogo inicial desde un archivo tabular validado antes de cargar, con errores reportados por línea.", "No es una integración con otro sistema.", "", "Catálogo textil", "SPEC · HU-014", "Catálogo; Bitácora de auditoría")

# ------------------------------------------------------------------ Lotes
T("Lote", "Conjunto de mercancía de un mismo SKU que ingresó en un mismo evento de entrada y comparte origen y condiciones. Permite rastrear un problema hasta su procedencia y se inmoviliza y libera como un todo.",
  "No es un lote de producción ni agrupa referencias, tallas o colores distintos.", "partida, tanda", "Trazabilidad", "SPEC · CD-06 · Monografía §7.1", "SKU; Unidad de inventario; Inmovilización; Documento de entrada", "L-2026-0142 de CAM-001 · M · Azul", True)
T("Código de lote", "Identidad de un lote, única dentro de su SKU; si la empresa no distingue lotes, el sistema genera uno por evento de entrada.", "No es único en todo el sistema, solo dentro del SKU.", "", "Trazabilidad", "SPEC · RN-014, RN-071", "Lote", "L-2026-0142")
T("Antigüedad de lote", "Días transcurridos desde la fecha de ingreso de un lote; sobre el umbral configurado genera alerta informativa.", "No es una fecha de vencimiento del producto (HD-10).", "", "Trazabilidad", "SPEC · RN-074", "Lote; Alerta")
T("Lote habilitado", "Estado del lote cuya existencia sigue sus estados normales (no inmovilizado).", "No significa «disponible»: la disponibilidad es un estado de la existencia.", "", "Trazabilidad", "Nuevo (Fase 4) · HD-19", "Lote; Inmovilización")

# ------------------------------------------------------------------ Espacio físico
T("Bodega", "Ámbito físico mayor donde se almacena inventario y ámbito de responsabilidad de un Jefe de Bodega; contiene zonas y al menos una zona de recepción.",
  "No es la empresa ni un almacén de un tercero.", "almacén (como sinónimo), depósito", "Ubicaciones", "SPEC · CD-12", "Zona; Ubicación; Jefe de Bodega", "Bodega Principal", True)
T("Zona", "Subdivisión de una bodega con propósito operativo: recepción, almacenamiento, preparación de salida o cuarentena. Agrupa ubicaciones y puede tener un Coordinador responsable.",
  "No es una ubicación ni un área administrativa de la empresa.", "área (HD-01), sector, pasillo", "Ubicaciones", "SPEC · CD-13", "Bodega; Ubicación; Tipo de zona; Coordinador de Bodega", "Zona Z2 · Almacenamiento", True)
T("Ubicación", "Posición física identificable dentro de una zona donde reside mercancía; tiene QR propio, capacidad y estado. Es el nivel mínimo de precisión espacial; toda existencia disponible reside en una.",
  "No es una zona completa ni la dirección de la empresa.", "posición, casilla, celda, slot, hueco", "Ubicaciones", "SPEC · CD-14", "Zona; Capacidad de ubicación; Identificador QR; Unidad de inventario", "Z2-E03-N2 (zona 2, estante 3, nivel 2)", True)
T("Capacidad de ubicación", "Cantidad máxima que admite una ubicación, expresada en la unidad configurada; se usa para proponer destinos y alertar sobreocupación.",
  "No es la existencia actual de la ubicación.", "cupo", "Ubicaciones", "SPEC · CD-15", "Ubicación; Ocupación; Sobreocupación", "200 unidades", True)
T("Zona de recepción", "Zona donde permanece la mercancía entre su llegada y su ubicación definitiva; su existencia está en el inventario pero no está disponible. Toda bodega tiene al menos una, y toda zona de recepción tiene al menos una ubicación.",
  "No es un lugar fuera del inventario ni existencia disponible.", "muelle, andén (como sinónimos)", "Ubicaciones", "SPEC · CD-16", "Inventario en recepción; Entrada", "Zona Z0 · Recepción", True)
T("Zona de cuarentena", "Zona donde reside mercancía inmovilizada: dañada, en verificación o pendiente de decisión. Su existencia no es disponible.",
  "No es una zona de baja ni implica que la mercancía salió del inventario.", "zona de rechazos", "Ubicaciones", "SPEC · CD-17", "Inmovilización; Novedad", "Zona ZQ · Cuarentena", True)
T("Zona de almacenamiento", "Zona destinada a mantener la existencia disponible en sus ubicaciones.", "—", "", "Ubicaciones", "SPEC · M-05", "Zona")
T("Zona de preparación", "Zona destinada a preparar salidas.", "—", "", "Ubicaciones", "SPEC · M-05", "Zona; Salida")
T("Tipo de zona", "Propósito operativo de una zona: recepción, almacenamiento, preparación de salida o cuarentena.", "No es un estado de la zona.", "", "Ubicaciones", "SPEC · M-05", "Zona")
T("Código de ubicación", "Identidad de una ubicación, única dentro de su bodega.", "No es único entre bodegas distintas.", "", "Ubicaciones", "SPEC · RN-014", "Ubicación")
T("Ubicación física", "Dirección completa Bodega › Zona › Ubicación de una existencia.", "No es la zona sola ni un texto libre.", "", "Ubicaciones", "Nuevo (Fase 4) · VO-10", "Bodega; Zona; Ubicación", "Bodega Principal › Z2 › Z2-E03-N2")
T("Ocupación", "Cantidad de existencia que aloja una ubicación frente a su capacidad.", "No es calculable entre unidades de medida distintas sin una regla de equivalencia (HD-17).", "", "Ubicaciones", "SPEC · KPI-18", "Capacidad de ubicación; Sobreocupación")
T("Sobreocupación", "Condición en que la ocupación de una ubicación supera su capacidad; genera alerta.", "No es un estado de la ubicación ni impide por sí sola registrar el movimiento ya hecho.", "", "Alertas y reglas", "SPEC · RN-021", "Capacidad de ubicación; Alerta")
T("Propuesta de ubicación", "Ubicación destino que el sistema sugiere según los criterios configurados (zona por categoría, capacidad, agrupación por referencia). Es sugerencia, no imposición.",
  "No obliga al operario ni su desviación es una falta.", "asignación obligatoria", "Ubicaciones", "SPEC · RN-020, PN-03", "Desviación de ubicación; Criterio de asignación")
T("Criterio de asignación", "Regla configurable, con orden de aplicación, que el sistema usa para proponer ubicación.", "No es una regla estructural.", "", "Ubicaciones", "SPEC · HU-024", "Propuesta de ubicación")
T("Desviación de ubicación", "Diferencia entre la ubicación propuesta y la confirmada; se registra como información operativa y no como falta imputable.", "No es un error del operario ni un indicador de desempeño individual `[PR-06]`.", "error de ubicación", "Ubicaciones", "SPEC · RN-022", "Propuesta de ubicación; KPI-10")

# ------------------------------------------------------------------ Existencia
T("Unidad de inventario", "La entidad que COLBASOFT controla: la combinación SKU + Lote + Ubicación. Nivel al que se registra existencia, se ejecutan movimientos y se lleva kardex. No tiene QR propio: se identifica con el QR de su SKU + Lote más su ubicación.",
  "No es «el inventario» completo, ni una prenda individual, ni un SKU, ni lo que identifica un QR de mercancía (DF5-01).", "inventario (como entidad, HD-01), ítem, artículo", "Inventario y existencia", "SPEC · CD-07", "SKU; Lote; Ubicación; Existencia; Kardex", "CAM-001 · M · Azul · L-2026-0142 · Z2-E03-N2", True)
T("Existencia", "Cantidad de una unidad de inventario presente en el sistema en un momento dado; siempre es la suma algebraica de sus movimientos confirmados, nunca un valor ingresado directamente.",
  "No es un valor que se escriba o corrija a mano.", "stock, saldo, disponible (como sustantivo genérico)", "Inventario y existencia", "SPEC · CD-18 · Monografía §7.1", "Kardex; Movimiento; Estado de inventario", "40 unidades", True)
T("Inventario disponible", "Porción de la existencia que puede comprometerse para una salida o transferencia: existencia menos reservado, inmovilizado, en tránsito y en recepción. Es la cifra que el operario ve por defecto.",
  "No es la existencia total.", "stock libre", "Inventario y existencia", "SPEC · CD-19", "Existencia; Reserva", "25 de 40", True)
T("Inventario reservado", "Porción de la existencia comprometida por una salida autorizada o una transferencia creada, aún no ejecutada. Sigue en la bodega pero no puede comprometerse otra vez.",
  "No es existencia que ya salió.", "apartado", "Inventario y existencia", "SPEC · CD-20", "Reserva; Solicitud de salida; Transferencia", "10 de 40", True)
T("Inventario inmovilizado", "Porción de la existencia que existe físicamente pero no puede moverse ni salir sin autorización expresa: dañada, en verificación, bloqueada o en cuarentena.",
  "No es existencia dada de baja.", "bloqueado (como sustantivo), congelado", "Inventario y existencia", "SPEC · CD-22", "Inmovilización; Zona de cuarentena; Lote", "5 de 40", True)
T("Inventario en tránsito", "Existencia que salió de una ubicación origen y aún no se confirmó en su destino; no está disponible en ninguna de las dos y tiene plazo máximo.",
  "No es existencia perdida ni ya recibida.", "en camino", "Inventario y existencia", "SPEC · CD-23", "Transferencia; Movimiento interno; Tiempo máximo en tránsito", "Despachado de Z1, sin recibir en Z3", True)
T("Inventario en recepción", "Existencia ya incorporada al inventario en la zona de recepción, aún no ubicada ni disponible; es donde queda toda entrada confirmada.", "No es disponible (DF5-02).", "", "Inventario y existencia", "SPEC · CD-16, CD-44", "Zona de recepción; Estado de inventario")
T("Inventario ajustado", "Existencia cuyo valor fue modificado por un movimiento de ajuste; la marca es consultable y se deriva del kardex.", "No es un estado de la existencia ni un error en sí mismo.", "", "Movimientos", "SPEC · CD-24", "Ajuste; Kardex")
T("Estado de inventario", "Condición de una porción de existencia que determina qué puede hacerse con ella: Disponible, Reservado, En tránsito, Inmovilizado o En recepción; mutuamente excluyentes para una misma cantidad.",
  "No es el estado de una referencia, de un lote ni de un documento.", "estatus de stock", "Inventario y existencia", "SPEC · CD-44", "Existencia; Inventario disponible", "Reservado", True)
T("Desglose de existencia", "Reparto de la existencia de una unidad entre sus estados; la suma de las porciones es la existencia derivada del kardex.", "No es un conjunto de valores independientes.", "", "Inventario y existencia", "Nuevo (Fase 4) · VO-15", "Estado de inventario")
T("Reserva", "Acto y resultado de comprometer existencia disponible para una salida autorizada o una transferencia creada; se libera al ejecutarse, cancelarse o vencer.", "No descuenta existencia.", "apartado", "Inventario y existencia", "SPEC · RN-031, RN-051", "Inventario reservado")
T("Existencia histórica", "Existencia reconstruida desde el kardex a una fecha de corte; da siempre el mismo resultado para la misma fecha.", "No es una copia guardada del pasado.", "", "Trazabilidad", "SPEC · HU-075", "Kardex; Fecha de corte")
T("Ruptura de stock", "Condición en que la existencia disponible de un SKU baja de su mínimo (ruptura inminente) o llega a cero. Término consagrado por la monografía; no sustituye a «existencia».",
  "No autoriza usar «stock» como sinónimo de existencia.", "quiebre, faltante (como sinónimo)", "Alertas y reglas", "Monografía §3 · SPEC PN-11", "Umbral de existencia mínima; KPI-21; Alerta")
T("Sobre stock", "Condición en que la existencia de un SKU supera su máximo configurado. Término consagrado por la monografía.", "No autoriza usar «stock» como sinónimo de existencia.", "exceso", "Alertas y reglas", "Monografía §3 · SPEC PN-11", "Umbral de existencia máxima; KPI-16")
T("Existencia sin movimiento", "Existencia que lleva más del umbral de días sin ningún movimiento.", "No es existencia inmovilizada.", "", "Reportes y medición", "SPEC · KPI-17", "Kardex")

# ------------------------------------------------------------------ Identificación
T("Identificador QR", "Código único generado por el sistema, asociado a un SKU + Lote (QR de mercancía) o a una ubicación (QR de ubicación); medio primario de interacción del operario. El de mercancía no identifica ubicación, bodega ni cantidad, y no cambia al reubicar. Es de un solo uso: nunca se repite ni se reutiliza. Estados: generado, activo, reemplazado, anulado.",
  "No es el código de barras del proveedor, ni un dato que el usuario digite, ni el identificador de una unidad de inventario (DF5-01).", "etiqueta (como sinónimo del código), código de barras", "Identificación", "SPEC · CD-08 · DC-08 · DF5-01", "Código QR; Identificador secundario; Lote; Unidad de inventario", "Etiqueta impresa con QR y texto legible «CAM-001 · M · Azul · L-2026-0142»", True)
T("Código QR", "Valor codificado de un identificador QR, irrepetible en toda la vida del sistema.", "No es reutilizable tras anulación o reemplazo.", "", "Identificación", "Nuevo (Fase 4) · VO-07", "Identificador QR")
T("Identificador secundario", "Código de barras u otro código externo asociado a mercancía; admitido para consulta, nunca para escritura, y asociado a lo sumo a un QR de mercancía (un SKU + Lote).",
  "No reemplaza al QR como identificador principal.", "", "Identificación", "SPEC · CD-09 · DC-08", "Identificador QR", "Código de barras del proveedor", True)
T("Escaneo", "Lectura de un identificador con la cámara de la tablet que resuelve el elemento identificado.", "No es un evento del dominio: leer no cambia estado.", "digitación", "Identificación", "SPEC · M-06", "Identificador QR; Selección manual")
T("Selección manual", "Identificación de mercancía o ubicación eligiéndola de una lista cuando el escaneo es imposible; queda registrada como tal.", "No es equivalente a un escaneo para efectos de KPI-07.", "", "Identificación", "SPEC · PN-03 E-05", "Escaneo; KPI-07")
T("Reimpresión", "Impresión de otra copia del mismo QR por deterioro o ilegibilidad, con motivo. Conserva el mismo identificador: no crea una nueva identidad ni cambia su estado, por lo que las demás copias del QR siguen válidas.", "No emite un código nuevo ni deja reemplazado el anterior (Q-09).", "reetiquetado", "Identificación", "SPEC · RN-018", "Identificador QR")
T("Unidad de manejo agrupada", "Término de la v1.0 para el contenedor rotulado que agrupa mercancía sin rotulado individual. Desde la v1.2 se modela como una pieza de tipo contenedor agrupado (HD-22 resuelto, F-6); su gestión avanzada sigue en el Horizonte 3.", "No es una entidad aparte del modelo del MVP.", "", "Identificación", "SPEC · PN-02 E-03 · Decisión F-6 (v1.2)", "Identificador QR; Pieza; Contenedor agrupado")

# ------------------------------------------------------------------ Movimientos
T("Movimiento", "Hecho registrado que altera la existencia o la ubicación de una unidad de inventario. Unidad transaccional del sistema; inmutable una vez confirmado. Nada cambia en el inventario sin un movimiento.",
  "No es cualquier acción del usuario ni un registro de bitácora.", "transacción, registro, apunte", "Movimientos", "SPEC · CD-28 · Monografía §8.2", "Kardex; Entrada; Salida; Ajuste; Anulación", "Movimiento interno de 5 unidades de Z2-E03-N2 a Z2-E04-N1", True)
T("Entrada", "Movimiento que incrementa la existencia por incorporación de mercancía procedente del exterior de la bodega.", "No es una compra ni una recepción física sin confirmar.", "ingreso, remisión (como sinónimos)", "Movimientos", "SPEC · CD-29 · Monografía §8.2", "Documento de entrada; Confirmación de entrada", "Entrada de 120 unidades del lote L-2026-0142", True)
T("Salida", "Movimiento que disminuye la existencia por retiro de mercancía hacia el exterior de la bodega, con motivo tipificado y autorización.", "No es una venta, un despacho comercial ni una factura `[DC-03]`.", "venta, despacho comercial", "Movimientos", "SPEC · CD-30 · Monografía §8.2", "Solicitud de salida; Motivo tipificado", "Salida de 30 unidades por consumo de producción", True)
T("Movimiento interno", "Movimiento que cambia la ubicación de existencia dentro de la misma bodega sin alterar la existencia total; incluye la primera ubicación de la mercancía en recepción.", "No es una transferencia entre ámbitos con responsables distintos.", "traslado, reubicación (como sinónimos del movimiento)", "Movimientos", "SPEC · CD-31", "Transferencia; Ubicación", "Z2-E03-N2 → Z2-E04-N1", True)
T("Transferencia", "Movimiento compuesto que traslada existencia entre zonas o bodegas con responsables distintos, mediante despacho y recepción, atravesando el estado en tránsito.",
  "No es un movimiento interno simple.", "traslado entre bodegas", "Movimientos", "SPEC · CD-32", "Despacho; Recepción de transferencia; Inventario en tránsito", "De Zona Z1 a Zona Z3", True)
T("Ajuste", "Movimiento que modifica la existencia sin contrapartida física para hacer coincidir el registro con la realidad; exige motivo tipificado y aprobación de un tercero y queda marcado para siempre. Es el movimiento de mayor riesgo.",
  "No es una edición del kardex ni una forma rutinaria de cuadrar el inventario.", "corrección, nivelación, cuadre", "Movimientos", "SPEC · CD-33 · Monografía §8.2", "Solicitud de ajuste; Motivo tipificado; Ajuste menor; Ajuste mayor", "Faltante de 2 unidades por daño, aprobado por el Jefe", True)
T("Anulación", "Movimiento inverso que neutraliza el efecto de un movimiento previo erróneo; no borra el original: ambos permanecen en el kardex. Requiere motivo y autorización.",
  "No es un borrado ni una edición.", "reversión, borrado, eliminación", "Trazabilidad", "SPEC · CD-34", "Movimiento; Kardex", "Anulación de una entrada registrada por duplicado", True)
T("Movimiento inverso", "Movimiento de cantidad y sentido opuestos a otro, usado para anularlo o para el retorno al origen de una transferencia cancelada en tránsito.", "No modifica el movimiento original.", "", "Trazabilidad", "SPEC · RN-012, RN-035", "Anulación")
T("Movimiento de excepción", "Movimiento autorizado por el Jefe durante el bloqueo de un conteo general y marcado como excepción en el kardex.", "No es un movimiento normal durante el conteo.", "", "Conteos y exactitud", "SPEC · RN-045", "Conteo general; Bloqueo de movimientos")
T("Documento de entrada", "Registro que agrupa la mercancía esperada en un evento de recepción, con origen, referencias y cantidades; soporte contra el cual se verifica lo recibido.",
  "No es una orden de compra ni un documento comercial `[DC-03]`.", "remisión, ingreso, recepción (como sustantivo)", "Movimientos", "SPEC · CD-35", "Entrada; Origen de entrada; Faltante de recepción; Sobrante de recepción", "DE-0087 · Taller externo · 120 unidades esperadas", True)
T("Origen de entrada", "Procedencia declarada de la mercancía que entra.", "No es un proveedor como entidad comercial `[DC-03]`.", "proveedor (como entidad)", "Movimientos", "SPEC · CD-35", "Documento de entrada")
T("Recepción física", "Conteo y registro, línea por línea, de la mercancía que llega contra el documento de entrada, hecho desde la tablet.", "No incorpora la mercancía al inventario: eso ocurre al confirmar.", "", "Movimientos", "SPEC · PN-01", "Documento de entrada; Confirmación de entrada")
T("Recepción parcial", "Estado del documento de entrada cuya recepción se interrumpió y puede continuar, incluso por otro usuario.", "No es una recepción con faltante.", "", "Movimientos", "SPEC · PN-01 E-06", "Documento de entrada")
T("Recibido conforme", "Estado del documento de entrada en el que lo recibido coincide con lo esperado.", "No es confirmado.", "", "Movimientos", "SPEC · PN-01", "Documento de entrada")
T("Recibido con novedad", "Estado del documento de entrada con faltante, sobrante o daño registrados.", "No es lo mismo que una novedad de mercancía.", "", "Movimientos", "SPEC · PN-01", "Faltante de recepción; Sobrante de recepción")
T("Faltante de recepción", "Diferencia en la que lo recibido es menor que lo esperado; se registra y notifica al Jefe sin bloquear la confirmación de lo recibido.", "No es un ajuste.", "", "Movimientos", "SPEC · RN-006", "Documento de entrada")
T("Sobrante de recepción", "Diferencia en la que lo recibido es mayor que lo esperado; no ingresa sin autorización del Jefe.", "No es un ajuste por sobrante.", "", "Movimientos", "SPEC · RN-007", "Documento de entrada; Jefe de Bodega")
T("Confirmación de entrada", "Verificación por una persona distinta de quien recibió, que incorpora la mercancía al inventario y genera lote y movimiento de entrada.", "No puede hacerla quien registró la recepción física.", "", "Movimientos", "SPEC · PN-01, RN-057b", "Segregación de funciones; Entrada")
T("Solicitud de salida", "Pedido interno de retirar mercancía, con motivo tipificado, que se autoriza, reserva, prepara y ejecuta.", "No es un pedido de venta `[DC-03]`.", "pedido, orden de venta", "Movimientos", "SPEC · M-08, RN-023", "Salida; Reserva; Preparación de salida")
T("Preparación de salida", "Toma física de la mercancía autorizada, guiada por la política de toma y validada por escaneo.", "No es la salida misma: la salida se registra al confirmar la preparación.", "picking", "Movimientos", "SPEC · PN-10", "Política de toma; Solicitud de salida")
T("Política de toma", "Criterio configurable para indicar de qué ubicación tomar en una salida: primero en entrar primero en salir por lote, ubicación de mayor cantidad o más próxima.", "No es una regla estructural.", "", "Movimientos", "SPEC · RN-049", "Preparación de salida")
T("Baja por daño", "Salida con motivo de daño que exige aprobación del Jefe, observación y evidencia cualquiera sea la cantidad; alimenta el reporte de mermas.", "No es un ajuste ni una salida ordinaria.", "merma (como sinónimo del movimiento)", "Movimientos", "SPEC · RN-052", "Salida; KPI-13")
T("Retorno", "Vuelta de mercancía que había salido; se registra como entrada nueva que referencia la salida original, sin reversar la salida.", "No es una anulación de la salida.", "devolución (como reversión)", "Movimientos", "SPEC · RN-053", "Entrada; Salida")
T("Despacho", "Confirmación, por escaneo del Auxiliar del origen, de que la mercancía de una transferencia salió; la pone en tránsito.", "No es una salida del inventario.", "", "Movimientos", "SPEC · PN-06", "Transferencia; Inventario en tránsito")
T("Recepción de transferencia", "Confirmación, por escaneo del Auxiliar del destino, de que la mercancía de una transferencia llegó; se compara con lo despachado.", "No es una entrada.", "", "Movimientos", "SPEC · PN-06", "Transferencia; Diferencia de transferencia")
T("Diferencia de transferencia", "Discrepancia entre lo despachado y lo recibido; si falta, abre novedad; si sobra, se rechaza la recepción; en ambos casos resuelve el Jefe.", "No se ajusta automáticamente.", "", "Movimientos", "SPEC · RN-033", "Transferencia; Novedad")
T("Tiempo máximo en tránsito", "Plazo configurable tras el cual una transferencia o un movimiento interno en tránsito genera alerta.", "No cancela la transferencia.", "", "Alertas y reglas", "SPEC · RN-028, RN-034", "Inventario en tránsito; Alerta")
T("Solicitud de ajuste", "Petición de corregir la existencia registrada, con motivo tipificado y evidencia, que se clasifica, se enruta y se aprueba o rechaza por un tercero.", "No cambia la existencia hasta su aprobación.", "", "Movimientos", "SPEC · PN-07", "Ajuste; Ajuste menor; Ajuste mayor")
T("Ajuste menor", "Ajuste por debajo del umbral configurado; lo aprueba el Jefe de Bodega.", "No lo aprueba quien lo solicitó.", "", "Movimientos", "SPEC · RN-024", "Solicitud de ajuste; Umbral")
T("Ajuste mayor", "Ajuste por encima del umbral configurado; lo aprueba el Administrador.", "No lo aprueba quien lo solicitó.", "", "Movimientos", "SPEC · RN-024", "Solicitud de ajuste; Umbral")
T("Ajuste por sobrante", "Ajuste que incorpora existencia encontrada sin registro, con motivo tipificado y aprobación del Jefe.", "No es una entrada.", "", "Novedades", "SPEC · RN-043", "Mercancía sin registro")
T("Motivo tipificado", "Causa seleccionada de una lista cerrada, obligatoria en ajustes, anulaciones, salidas, inmovilizaciones, cancelaciones y descartes de alerta. El texto libre nunca lo sustituye.",
  "No es un comentario libre.", "razón libre, observación (como sustituto)", "Configuración", "SPEC · CD-36", "Ajuste; Salida; Evidencia; Justificación", "«Faltante por daño en manipulación»", True)
T("Motivo aplicado", "Motivo tipificado seleccionado en una operación, junto con el texto complementario opcional.", "No es solo texto libre.", "", "Movimientos", "Nuevo (Fase 4) · VO-22", "Motivo tipificado")
T("Evidencia", "Adjunto (fotografía o documento) que respalda una solicitud; obligatoria cuando el motivo lo exige.", "No es opcional si el motivo la exige.", "", "Movimientos", "SPEC · RN-029, RN-052", "Motivo tipificado; Ajuste")
T("Justificación", "Texto obligatorio que explica una decisión de rechazo, descarte, exclusión o cancelación.", "No sustituye a un motivo tipificado.", "", "Transversal", "SPEC · RN-062, RN-046", "Motivo tipificado")
T("Documento de respaldo", "Documento del dominio que originó un movimiento (documento de entrada, solicitud de salida, transferencia, solicitud de ajuste o conteo).", "No es un documento comercial.", "soporte comercial", "Trazabilidad", "SPEC · CD-37", "Movimiento; Kardex")
T("Cantidad", "Magnitud de existencia o de movimiento expresada en la unidad de medida de su referencia.", "No se convierte entre unidades.", "", "Transversal", "Nuevo (Fase 4) · VO-13", "Unidad de medida")

# ------------------------------------------------------------------ Trazabilidad
T("Kardex", "Registro cronológico, completo e inmutable de todos los movimientos de una unidad de inventario desde su creación. Es la fuente de verdad de la existencia: la existencia se deriva del kardex, nunca al revés.",
  "No es la bitácora del sistema ni un reporte editable.", "log, historial (de inventario), libro", "Trazabilidad", "SPEC · CD-37 · Monografía §7.1, §8.2", "Movimiento; Existencia; Trazabilidad", "Línea: 2026-10-05 09:42 · Entrada · +120 · 120 · Z0-R01 · Coordinador A · DE-0087", True)
T("Trazabilidad", "Capacidad de responder, para cualquier unidad de inventario y cualquier momento pasado, qué es, cuánto había, dónde estaba, quién la movió, cuándo y por qué. Es retrospectiva y completa, desde la entrada hasta la salida de bodega.",
  "No cubre la cadena de suministro aguas arriba ni la distribución aguas abajo `[DC-03]`.", "rastreo (como alcance mayor)", "Trazabilidad", "SPEC · CD-21 · Monografía §2, §6, §7.1", "Kardex; Lote; Verificación de integridad", "¿Quién movió el lote L-2026-0142 a cuarentena y por qué?", True)
T("Verificación de integridad", "Comprobación, por unidad, lote o global, de que la existencia actual es igual a la suma de los movimientos del kardex.", "No corrige nada: solo detecta.", "cuadre", "Trazabilidad", "SPEC · RN-065, RN-080", "Kardex; Discrepancia de integridad; KPI-09")
T("Discrepancia de integridad", "Diferencia entre la existencia y la suma de movimientos de una unidad, un lote o el total; es hallazgo crítico.", "No es una diferencia de conteo.", "lote inconsistente (HD-14)", "Trazabilidad", "SPEC · RN-065", "Verificación de integridad; Hallazgo crítico")
T("Fecha operativa", "Instante (fecha y hora) en que ocurrió un hecho, con su jornada; distinto del instante en que se sincronizó.", "No es la fecha de sincronización (HD-16).", "", "Transversal", "Nuevo (Fase 4) · VO-32", "Movimiento; Sincronización")
T("Fecha de corte", "Instante de referencia de un conteo general o de una consulta histórica, declarado en todo resultado que lo use.", "—", "", "Transversal", "SPEC · PN-09, HU-075", "Conteo general; Existencia histórica")
T("Retención local", "Conservación en el dispositivo de un registro hecho sin conectividad, hasta sincronizarlo.", "No confirma el registro.", "", "Trazabilidad", "SPEC · RN-054", "Sincronización")
T("Sincronización", "Envío al sistema de los registros retenidos al restablecerse la conectividad; cada uno se valida de nuevo contra el estado vigente y se confirma, conservando su fecha operativa, o se rechaza.", "No altera el orden ni el contenido del hecho.", "", "Trazabilidad", "SPEC · RN-054", "Retención local; Pendiente de sincronización")
T("Pendiente de sincronización", "Estado de un movimiento registrado sin conectividad; impide confirmar documentos y cerrar la jornada.", "No es un movimiento confirmado.", "", "Trazabilidad", "SPEC · RN-054", "Movimiento; Sincronización")

# ------------------------------------------------------------------ Conteos
T("Conteo", "Proceso de verificación de la existencia física contra la registrada sobre un ámbito definido; estados: programado, en ejecución, en conciliación, cerrado, abortado o vencido.",
  "No es un ajuste ni modifica la existencia por sí mismo.", "toma física, inventario físico (como verbo)", "Conteos y exactitud", "SPEC · CD-38 · Monografía §8.2", "Conteo cíclico; Conteo general; Exactitud del inventario", "Conteo de la Zona Z2", True)
T("Conteo cíclico", "Conteo de un ámbito parcial (ubicaciones, referencias o categorías) ejecutable sin detener la operación. Mecanismo continuo de medición de exactitud.",
  "No bloquea movimientos.", "inventario rotativo", "Conteos y exactitud", "SPEC · CD-39", "Conteo; KPI-01", "Conteo semanal de la categoría Camisetas", True)
T("Conteo general", "Conteo de la totalidad del inventario, que bloquea el registro de movimientos desde el corte hasta el cierre.", "No es un conteo cíclico grande.", "inventario anual", "Conteos y exactitud", "SPEC · CD-40", "Bloqueo de movimientos; KPI-02", "Conteo general del 31 de diciembre", True)
T("Tarea de conteo", "Unidad de trabajo asignada a un contador sobre un subconjunto del ámbito del conteo.", "No muestra la cantidad esperada.", "", "Conteos y exactitud", "SPEC · CD-41", "Contador; Conteo", "Contar Z2-E03 (niveles 1 a 4)", True)
T("Segundo conteo", "Repetición de una tarea de conteo ejecutada obligatoriamente por un contador distinto del primero cuando la diferencia supera la tolerancia.", "No lo hace quien hizo el primero.", "reconteo por la misma persona", "Conteos y exactitud", "SPEC · CD-42", "Umbral de tolerancia; Segregación de funciones", "Recuento de Z2-E03-N2 por otro Auxiliar", True)
T("Existencia teórica congelada", "Fotografía de la existencia tomada al iniciar un conteo contra la cual se compara lo contado; no se altera por movimientos posteriores.", "No se muestra al contador.", "saldo congelado", "Conteos y exactitud", "SPEC · CD-25", "Conteo; Diferencia de inventario", "Unidad Z2-E03-N2: 40, tomada el 2026-10-05 07:00", True)
T("Existencia contada", "Cantidad física registrada por un contador; solo modifica la existencia si el cierre genera un ajuste aprobado.", "No es un estado del inventario.", "", "Conteos y exactitud", "SPEC · CD-26", "Tarea de conteo; Diferencia de inventario", "38 unidades contadas", True)
T("Diferencia de inventario", "Existencia contada menos existencia teórica congelada; positiva es sobrante, negativa es faltante.", "No es automáticamente un ajuste.", "descuadre", "Conteos y exactitud", "SPEC · CD-27", "Conteo; Ajuste; KPI-04", "−2 (faltante)", True)
T("Exactitud del inventario", "Proporción de líneas contadas cuya existencia contada coincide con la teórica congelada; es el KPI-01 y el indicador central del compromiso de valor.",
  "No tiene meta numérica hasta existir línea base.", "precisión (como sinónimo del KPI)", "Conteos y exactitud", "SPEC · CD-43 · Monografía §8.2", "KPI-01; Conteo; Línea base", "92,5 %", True)
T("Conciliación", "Revisión de las diferencias de un conteo, considerando los movimientos ocurridos durante su ejecución, antes del cierre.", "No modifica la existencia congelada.", "", "Conteos y exactitud", "SPEC · PN-08", "Conteo; Existencia teórica congelada")
T("Contador", "Persona asignada a una tarea de conteo.", "No es un rol: es una función que cumple un usuario.", "", "Conteos y exactitud", "SPEC · RN-040", "Tarea de conteo; Segundo conteo")
T("Umbral de tolerancia", "Diferencia máxima admitida en una línea de conteo antes de exigir segundo conteo.", "No es la exactitud objetivo.", "", "Conteos y exactitud", "SPEC · RN-041", "Segundo conteo")
T("Cobertura de conteo", "Proporción del inventario verificada en el período, o de ubicaciones cubiertas en un conteo general.", "—", "", "Conteos y exactitud", "SPEC · KPI-03, RN-046", "Conteo general")
T("Exclusión de ubicación", "Retiro justificado de una ubicación del alcance de un conteo general para permitir su cierre.", "No se permite sin justificación.", "", "Conteos y exactitud", "SPEC · RN-046", "Conteo general; Justificación")
T("Bloqueo de movimientos", "Impedimento de registrar movimientos entre el corte y el cierre de un conteo general, salvo excepciones del Jefe.", "No aplica al conteo cíclico.", "", "Conteos y exactitud", "SPEC · RN-045", "Conteo general; Movimiento de excepción")
T("Resultado de línea de conteo", "Clasificación de una línea contada: conforme, sobrante o faltante.", "—", "", "Conteos y exactitud", "SPEC · PN-08", "Diferencia de inventario")
T("Conteo abortado", "Conteo detenido por el Jefe sin generar ajustes; sus conteos parciales se conservan como evidencia.", "No es un conteo cerrado.", "", "Conteos y exactitud", "SPEC · PN-09 E-04", "Conteo")
T("Conteo vencido", "Conteo no ejecutado o no cerrado dentro de su plazo; al exceder el máximo se libera la existencia congelada.", "—", "", "Conteos y exactitud", "SPEC · RN-044", "Conteo; Alerta")

# ------------------------------------------------------------------ Control
T("Inmovilización", "Acto de impedir que una porción de existencia —o un lote completo— se mueva o salga sin autorización expresa.", "No es una baja ni una salida.", "bloqueo", "Inventario y existencia", "SPEC · RN-036", "Inventario inmovilizado; Liberación")
T("Liberación", "Acto de devolver a sus estados normales la existencia de un lote inmovilizado; solo Jefe o Administrador, con motivo tipificado.", "—", "desbloqueo", "Trazabilidad", "SPEC · RN-073", "Inmovilización; Lote")
T("Novedad", "Reporte de una anomalía física observada por un operario que el sistema no puede detectar por sí solo; también la abre el Sistema al rechazar en la sincronización un registro que describe un hecho físico ya realizado. Nunca se elimina: se cierra. No se imputa al reportante.",
  "No es una alerta (las alertas las genera el sistema) ni una falta del operario.", "reclamo, incidente (como sinónimos)", "Novedades", "SPEC · CD-48", "Tipo de novedad; Ajuste; Mercancía sin registro", "«Bolsa rota en Z2-E03-N2, 3 unidades manchadas»", True)
T("Tipo de novedad", "Clase de anomalía reportada: dañada, sin identificador, en ubicación incorrecta o inexistente (lista tipificada).", "—", "", "Novedades", "SPEC · PN-12", "Novedad")
T("Mercancía sin registro", "Mercancía encontrada en la bodega que no existe en el sistema; no se cuenta ni se usa hasta ser identificada e incorporada por ajuste por sobrante aprobado.", "No es un sobrante de recepción.", "", "Novedades", "SPEC · RN-043", "Ajuste por sobrante; Novedad")
T("Alerta", "Notificación generada automáticamente cuando una regla de negocio evalúa verdadera su condición de disparo. Manifestación operativa de la «inteligencia» del producto.",
  "No es una predicción ni el resultado de un modelo de aprendizaje `[DC-07]`; no es una novedad.", "aviso inteligente, predicción", "Alertas y reglas", "SPEC · CD-45 · DC-07", "Umbral; Tipo de alerta; Severidad", "Ruptura inminente de CAM-001 · M · Azul (18 < 30)", True)
T("Umbral", "Valor configurable por el Administrador que define cuándo dispara una regla: mínimo y máximo de existencia, tolerancia, monto de ajuste, tiempo en tránsito, plazos.",
  "No es una meta de desempeño.", "meta, objetivo", "Configuración", "SPEC · CD-46", "Parámetro de configuración; Alerta", "Tolerancia de conteo = 2 unidades", True)
T("Tipo de alerta", "Condición de negocio que representa una alerta; el MVP define diez tipos.", "—", "", "Alertas y reglas", "SPEC · PN-11", "Alerta")
T("Severidad", "Importancia de una alerta; incluye al menos el nivel «crítica», que escala por plazo. Los demás niveles no están definidos (HD-15).", "No es la prioridad de una tarea.", "", "Alertas y reglas", "SPEC · RN-056", "Alerta; Escalamiento")
T("Atención de alerta", "Registro de la acción correctiva ejecutada ante una alerta: quién, cuándo y qué.", "—", "", "Alertas y reglas", "SPEC · RN-058", "Alerta")
T("Descarte de alerta", "Cierre manual de una alerta sin acción correctiva, que exige motivo.", "No se permite sin motivo.", "", "Alertas y reglas", "SPEC · RN-058", "Alerta; Motivo tipificado")
T("Cierre automático de alerta", "Cierre de una alerta cuando su condición deja de cumplirse; queda marcada como no atendida si nadie actuó.", "—", "", "Alertas y reglas", "SPEC · RN-057", "Alerta")
T("Escalamiento", "Traslado automático de una alerta, solicitud o novedad al rol superior al vencer su plazo o al coincidir solicitante y aprobador.", "No es una reasignación manual.", "", "Transversal", "SPEC · RN-023, RN-038, RN-056, RN-059", "Plazo; Rol")
T("Plazo", "Duración máxima configurable de un estado (tránsito, reserva, aprobación, novedad, conteo, atención de alerta, inactividad).", "—", "", "Configuración", "SPEC · M-19", "Escalamiento; Parámetro de configuración")
T("Regla de negocio", "Enunciado explícito que el sistema evalúa para impedir estados inválidos, disparar alertas o ejecutar acciones sin intervención humana. Es el corazón de la «inteligencia» del producto.",
  "No es un modelo predictivo ni lógica oculta.", "algoritmo inteligente", "Alertas y reglas", "SPEC · Cap. 9 · SRS Cap. 8", "Regla estructural; Regla configurable; Invariante", "RN-EXI-001: ninguna operación deja existencia negativa", True)
T("Regla estructural", "Regla inviolable y no parametrizable; ningún rol puede eludirla, incluido el Administrador.", "No se configura (DEC-04: toda regla estructural es no configurable).", "", "Alertas y reglas", "SPEC · §9.1", "Regla de negocio; Invariante")
T("Regla configurable", "Regla cuyo umbral se ajusta en la configuración pero cuya lógica no puede desactivarse.", "No es desactivable.", "", "Alertas y reglas", "SPEC · §9", "Regla de negocio; Umbral")
T("Inteligente", "En COLBASOFT significa exactamente automatización basada en reglas y analítica operativa por indicadores.", "No significa aprendizaje automático, predicción, visión por computador, procesamiento de lenguaje natural ni IA generativa `[DC-07]`.", "inteligencia artificial, IA", "Proyecto", "SPEC · §1.6 · DC-07", "Regla de negocio; KPI; Alerta")

# ------------------------------------------------------------------ Auditoría
T("Bitácora de auditoría", "Registro inmutable de toda acción relevante del sistema, incluidas las que no alteran el inventario: accesos, configuración, roles, aprobaciones, rechazos, anulaciones y exportaciones. No es editable por ningún rol.",
  "No es el kardex ni un registro técnico de errores.", "log, historial de sistema", "Auditoría", "SPEC · CD-47", "Registro de bitácora; Kardex; Hallazgo crítico", "«2026-10-05 10:15 · Administrador B · umbral de ajuste mayor 40 → 50»", True)
T("Registro de bitácora", "Cada constancia individual de la bitácora; se agrega y nunca se modifica.", "No se edita ni se purga.", "", "Auditoría", "Nuevo (Fase 4) · E-21", "Bitácora de auditoría")
T("Observación de auditoría", "Hallazgo o comentario del Auditor sobre un movimiento, unidad, período o usuario, guardado en un registro separado que no altera el inventario; se cierra con respuesta.",
  "No es una corrección del inventario.", "ajuste del auditor", "Auditoría", "SPEC · RN-064", "Auditor; Bitácora de auditoría", "«Tres ajustes de la misma unidad en una semana, aprobados por la misma persona»", True)
T("Hallazgo crítico", "Resultado de auditoría que indica una falla de integridad o de segregación: discrepancia de integridad, aprobación propia, movimiento sin usuario atribuible o discontinuidad de bitácora.", "No es una observación ordinaria.", "", "Auditoría", "SPEC · PN-13", "Verificación de integridad; Aprobación propia")
T("Aprobación propia", "Caso en que quien originó una solicitud la aprueba; la regla lo impide y, si se detecta, es hallazgo crítico.", "No es permisible con ningún rol.", "autoaprobación permitida", "Auditoría", "SPEC · RN-023", "Segregación de funciones")
T("Alcance de auditoría", "Período, referencias, ubicaciones, usuarios o tipos de movimiento que el Auditor revisa.", "—", "campaña (no modelada como entidad, HD)", "Auditoría", "SPEC · PN-13", "Observación de auditoría")
T("Segregación de funciones", "Principio por el cual quien ejecuta una acción no es quien la autoriza.", "No es una recomendación opcional.", "", "Transversal", "SPEC · PR-01", "Aprobación propia; Confirmación de entrada; Segundo conteo")
T("Atribución", "Propiedad de toda acción que altera el estado de estar asignada a un usuario identificado o al Sistema como actor explícito.", "No admite cuentas compartidas.", "", "Transversal", "SPEC · PR-05, RN-001", "Actor; Usuario")
T("Eliminación lógica", "Principio por el cual nada se borra: los elementos se desactivan o se cierran y conservan su identidad histórica.", "No existe borrado físico.", "borrado", "Transversal", "SPEC · RN-063", "Desactivación; Reactivación")
T("Desactivación", "Paso de un elemento a estado inactivo: deja de participar en operaciones nuevas y conserva su historia.", "No es eliminar.", "eliminación, baja (de un maestro)", "Transversal", "SPEC · RN-063, RN-076", "Eliminación lógica; Reactivación")
T("Reactivación", "Vuelta de un elemento inactivo a estado activo, registrada en bitácora.", "—", "", "Transversal", "SPEC · RN-077", "Desactivación")
T("Exportación de datos", "Extracción de datos del sistema en formato tabular o estructurado; siempre queda en la bitácora con usuario, alcance y fecha.", "No elude las restricciones de visibilidad por rol.", "", "Reportes y medición", "SPEC · RN-078", "Bitácora de auditoría; Herramienta analítica externa")

# ------------------------------------------------------------------ Usuarios, roles, actores
T("Usuario", "Persona identificada que opera el sistema con exactamente uno de los cinco roles oficiales y un ámbito; nunca se elimina.", "No es una cuenta genérica o compartida.", "cuenta compartida", "Usuarios y acceso", "SPEC · M-02", "Rol; Ámbito; Sesión", "Usuario «aux.gomez» · Auxiliar de Bodega · Zona Z2", True)
T("Rol", "Función oficial de un usuario; existen exactamente cinco: Administrador, Jefe de Bodega, Coordinador de Bodega, Auxiliar de Bodega y Auditor.", "No se crean roles adicionales `[DC-04]`; el Sistema no es un rol.", "perfil (como sinónimo), cargo", "Usuarios y acceso", "SPEC · DC-04", "Usuario; Segregación de funciones", "Coordinador de Bodega", True)
T("Administrador", "Rol que configura el sistema, gestiona usuarios, roles y estructura de bodega, y aprueba ajustes mayores; decisor de compra.", "No puede editar movimientos ni la bitácora ni aprobar lo que solicitó.", "superusuario", "Usuarios y acceso", "SPEC · ROL-01", "Rol; Ajuste mayor")
T("Jefe de Bodega", "Rol responsable de la exactitud del inventario: aprueba ajustes menores, autoriza salidas, cierra conteos y resuelve diferencias.", "No gestiona usuarios ni la estructura de la bodega.", "", "Usuarios y acceso", "SPEC · ROL-02", "Rol; Conteo; Ajuste menor")
T("Coordinador de Bodega", "Rol de mando medio en piso: confirma entradas, asigna ubicaciones, crea transferencias, programa conteos cíclicos, solicita ajustes y autoriza salidas bajo su umbral.", "No aprueba sus propios ajustes ni cierra conteos.", "supervisor (como sinónimo del rol)", "Usuarios y acceso", "SPEC · ROL-03", "Rol; Zona")
T("Auxiliar de Bodega", "Rol del operario que mueve físicamente la mercancía; opera solo desde tablet. Es el usuario crítico del producto.", "No ve costos ni indicadores de desempeño individual; no aprueba nada.", "operario (como nombre de rol)", "Usuarios y acceso", "SPEC · ROL-04", "Rol; Usuario crítico; Panel de tareas")
T("Auditor", "Rol de revisión independiente con lectura completa y sin ninguna escritura sobre el inventario; su única escritura son observaciones de auditoría.", "No aprueba, no ajusta, no configura.", "", "Usuarios y acceso", "SPEC · ROL-05, PR-02", "Rol; Observación de auditoría")
T("Sistema (actor)", "Actor explícito al que se atribuyen las acciones automáticas: cierres de alertas, escalamientos, liberación de reservas vencidas, generación de tareas, cálculo de indicadores.", "No es un sexto rol ni tiene permisos (HD-12).", "usuario del sistema, robot", "Transversal", "SPEC · RN-001", "Actor; Evento derivado")
T("Actor", "Quien ejecuta un hecho: un usuario identificado o el Sistema.", "Nunca vacío ni compartido.", "", "Transversal", "Nuevo (Fase 4) · VO-38", "Usuario; Sistema (actor)")
T("Ámbito", "Bodega y zonas en que un usuario opera; filtra consultas y tareas. Jefe, Administrador y Auditor no tienen restricción de ámbito de consulta.", "—", "", "Usuarios y acceso", "SPEC · HU-008", "Usuario; Zona")
T("Sesión", "Período de trabajo autenticado de un usuario en un dispositivo; se cierra manualmente, por inactividad o por cambio de contraseña.", "No se comparte entre personas.", "", "Usuarios y acceso", "SPEC · M-01", "Usuario; Atribución")
T("Usuario crítico", "El Auxiliar de Bodega: quien más usa el sistema, menos formación tiene y más puede hacer fracasar su adopción.", "—", "", "Proyecto", "SPEC · §1.3.2 · Monografía §4", "Auxiliar de Bodega; Adopción")
T("Contraseña", "Credencial individual y secreta del usuario; su valor original no es recuperable por ningún medio.", "No se registra en bitácora ni se muestra.", "", "Usuarios y acceso", "SPEC · RNF-002", "Usuario; Sesión")

# ------------------------------------------------------------------ Tareas y operación
T("Tarea operativa", "Unidad de trabajo asignada a una persona (recepción, ubicación, preparación, transferencia) que indica qué, dónde y cuánto; se cierra por el hecho asociado, nunca por declaración.", "No se cierra marcándola como hecha.", "pendiente (como sustantivo)", "Tareas y notificaciones", "SPEC · M-20", "Panel de tareas; Reasignación")
T("Panel de tareas", "Vista del usuario con sus tareas ordenadas por prioridad; es lo único que ve el Auxiliar en lugar del dashboard.", "No muestra indicadores de desempeño individual.", "", "Tareas y notificaciones", "SPEC · HU-092", "Tarea operativa; Auxiliar de Bodega")
T("Reasignación", "Cambio del responsable de una tarea, registrando a ambos y sin violar la regla del segundo conteo.", "—", "", "Tareas y notificaciones", "SPEC · HU-103", "Tarea operativa; Segundo conteo")
T("Notificación", "Aviso dentro del sistema web al usuario que debe actuar o conocer un resultado; no expone información fuera de su ámbito.", "No es una aplicación móvil nativa `[DC-05]`.", "push", "Tareas y notificaciones", "SPEC · M-20", "Tarea operativa; Alerta")
T("Prioridad de tarea", "Orden en que el panel presenta las tareas; su escala no está definida (HD-15).", "No es la severidad de una alerta.", "", "Tareas y notificaciones", "SPEC · HU-092", "Panel de tareas")
T("Jornada", "Período operativo diario de la bodega al que pertenecen los hechos y que termina con el cierre de jornada.", "—", "", "Operación diaria", "SPEC · PN-14", "Cierre de jornada; Turno")
T("Turno", "Fracción de la jornada asignada a un equipo; los pendientes se traspasan explícitamente al siguiente.", "—", "", "Operación diaria", "SPEC · PN-14", "Jornada")
T("Cierre de jornada", "Consolidación de la actividad del día que deja la bodega en estado consistente y traspasa los pendientes al turno siguiente.", "No puede ejecutarse con registros sin sincronizar.", "", "Operación diaria", "SPEC · PN-14", "Jornada; Pendiente de sincronización")

# ------------------------------------------------------------------ Configuración
T("Parámetro de configuración", "Valor configurable por el Administrador, dentro de un rango admisible, que gobierna umbrales, plazos y políticas; su cambio queda en bitácora y no es retroactivo.", "No alcanza las reglas estructurales.", "", "Configuración", "SPEC · M-19", "Umbral; Plazo; Regla configurable")
T("Umbral de autorización del Coordinador", "Cantidad bajo la cual el Coordinador puede autorizar salidas; por encima autoriza el Jefe.", "—", "", "Configuración", "SPEC · RN-030", "Salida; Coordinador de Bodega")

# ------------------------------------------------------------------ Medición y proyecto
T("KPI", "Indicador operativo calculado por el sistema sobre su propio registro; existen 24 y ninguno tiene meta numérica sin línea base.", "No es una meta ni un indicador de desempeño individual ante el operario.", "métrica de desempeño personal", "Reportes y medición", "SPEC · Cap. 10", "Exactitud del inventario; Línea base", "KPI-08 Frecuencia de errores de registro", True)
T("Tiempo de registro", "Duración desde que un operario inicia un movimiento hasta que el sistema lo confirma; es el KPI-05.", "No se mide sin el instante de inicio (PROP-KPI-01 del SRS).", "", "Reportes y medición", "SPEC · KPI-05 · Monografía §8.2", "KPI; Movimiento")
T("Frecuencia de errores de registro", "Ajustes correctivos, movimientos anulados y líneas de conteo con diferencia sobre el total de movimientos; es el KPI-08.", "No se desglosa por persona ante el operario `[PR-06]`.", "tasa de error del operario", "Reportes y medición", "SPEC · KPI-08 · Monografía §8.2", "KPI; Ajuste; Anulación")
T("Línea base", "Medición del desempeño antes de implantar el sistema; no existe aún y sin ella los KPI-01, 05 y 08 no demuestran mejora.", "No es una meta.", "", "Proyecto", "SPEC · §13.1 · Auditoría C.2.4", "KPI; Empresa de estudio")
T("Reporte", "Información consolidada generada a demanda o programada, que declara fecha, hora y usuario de generación; nunca modifica datos.", "No es un tablero analítico `[DC-06]`.", "dashboard analítico", "Reportes y medición", "SPEC · M-16", "Exportación de datos; KPI")
T("Dashboard operativo", "Vista inmediata por rol del estado de la bodega y de lo que requiere atención: existencia por estado, alertas, pendientes y exactitud vigente.", "No es el tablero analítico de la herramienta externa `[DC-06]`.", "tablero de BI", "Reportes y medición", "SPEC · M-17", "Panel de tareas; Alerta")
T("Herramienta analítica externa", "Sistema externo (Power BI) al que COLBASOFT expone datos estructurados; allí se construyen los tableros analíticos.", "No forma parte del dominio de COLBASOFT.", "", "Reportes y medición", "SPEC · DC-06", "Exportación de datos")
T("Adopción escalonada", "Posibilidad de empezar a operar por procesos (entradas y salidas primero) y habilitar el resto después.", "No es una implantación completa de una sola vez.", "", "Proyecto", "SPEC · RNF-024 · Monografía §8.2", "Adopción")
T("Adopción", "Grado en que la operación real pasa efectivamente por el sistema; se mide con el KPI-24 y verificación de campo.", "—", "", "Proyecto", "SPEC · KPI-24 · Monografía §4", "Usuario crítico; KPI")
T("Empresa de estudio", "Organización del sector textil del Eje Cafetero con la que se levanta el proceso real y se opera el piloto, sin identificación comercial.", "No se nombra `[DC-01]`.", "cliente, empresa X", "Proyecto", "SPEC · DC-01", "Línea base")
T("MVP", "Conjunto mínimo con el que la bodega opera íntegramente en el sistema, con trazabilidad completa y capacidad de medir su impacto.", "No incluye ventas, compras completas, producción, contabilidad, nómina, CRM, facturación ni IA `[DC-03]` `[DC-07]`.", "", "Proyecto", "SPEC · §12.2 · SRS Cap. 12", "Decisión constitucional")
T("Automatización", "Uso de tecnologías para ejecutar tareas repetitivas sin intervención humana, con niveles parciales y totales.", "En COLBASOFT no incluye IA `[DC-07]`.", "", "Proyecto", "Monografía §7.1 · SPEC", "Inteligente; Regla de negocio")
T("Gestión de inventarios", "Control de existencias para equilibrar disponibilidad de materiales y costos y prevenir rupturas o excesos.", "No incluye la valorización contable en el MVP (HD-09).", "", "Proyecto", "Monografía §7.1", "Existencia; Ruptura de stock; Sobre stock")
T("Resistencia a la automatización", "Barreras culturales, financieras y técnicas que retrasan la adopción de tecnologías; razón de los requisitos de usabilidad y del principio «registrar, no castigar».", "—", "", "Proyecto", "Monografía §7.1", "Adopción; Usuario crítico")
T("PYME textil", "Pequeña o mediana empresa del sector textil; su definición legal para el proyecto sigue pendiente (A-03).", "—", "", "Proyecto", "Monografía §5", "Empresa de estudio")

# ------------------------------------------------------------------ Modelado (DDD)
T("Lenguaje ubicuo", "Vocabulario oficial y único del dominio, compartido por negocio y equipo, que se usa sin sinónimos en documentos, conversaciones e interfaz.", "No admite sinónimos ni términos técnicos de implementación.", "", "Modelado", "Nuevo (Fase 4)", "Hallazgo del dominio")
T("Subdominio", "Área del negocio con problemática propia; se clasifica como núcleo, de soporte o genérico.", "No es un módulo ni un componente técnico.", "", "Modelado", "Nuevo (Fase 4)", "Subdominio núcleo; Subdominio de soporte; Subdominio genérico")
T("Subdominio núcleo", "Subdominio donde está la ventaja del producto y donde se concentra el esfuerzo de modelado (Core Domain).", "—", "core", "Modelado", "Nuevo (Fase 4)", "Subdominio")
T("Subdominio de soporte", "Subdominio específico del negocio que el núcleo necesita pero que no es en sí la ventaja (Supporting Domain).", "—", "", "Modelado", "Nuevo (Fase 4)", "Subdominio")
T("Subdominio genérico", "Subdominio con problemas resueltos de forma general en cualquier sistema (Generic Domain).", "—", "", "Modelado", "Nuevo (Fase 4)", "Subdominio")
T("Entidad", "Elemento del dominio con identidad propia que persiste a través de sus cambios de estado.", "No es una estructura de almacenamiento.", "", "Modelado", "Nuevo (Fase 4)", "Objeto de valor; Agregado")
T("Objeto de valor", "Elemento del dominio definido solo por sus atributos, sin identidad propia e inmutable: para cambiarlo se reemplaza.", "No tiene ciclo de vida propio.", "", "Modelado", "Nuevo (Fase 4)", "Entidad")
T("Agregado", "Conjunto de entidades y objetos de valor que se modifica como una unidad para proteger sus invariantes; se accede por su raíz.", "No es un módulo funcional.", "", "Modelado", "Nuevo (Fase 4)", "Raíz de agregado; Invariante")
T("Raíz de agregado", "Entidad por la que se accede y se modifica un agregado; guardiana de sus invariantes.", "—", "", "Modelado", "Nuevo (Fase 4)", "Agregado")
T("Invariante", "Condición del dominio que debe cumplirse siempre, antes y después de cualquier cambio.", "No es una política reactiva (que actúa cuando algo ocurre).", "", "Modelado", "Nuevo (Fase 4)", "Regla de negocio; Política del dominio")
T("Política del dominio", "Regla reactiva del tipo «cuando ocurre X, entonces Y» (por ejemplo, escalar al vencer un plazo); se manifiesta como evento derivado.", "No es una invariante.", "", "Modelado", "Nuevo (Fase 4)", "Evento derivado; Invariante")
T("Evento de dominio", "Hecho relevante para el negocio que ya ocurrió, con nombre en pasado, actor, entidad de origen y resultado; tiene ID permanente EV-<DOM>-nnn.", "No es una acción (intención) ni un movimiento (que es un tipo particular de hecho sobre la existencia).", "", "Modelado", "Nuevo (Fase 4)", "Acción; Movimiento; Evento derivado", "EV-ENT-012 Entrada confirmada", True)
T("Evento derivado", "Evento que el Sistema genera automáticamente cuando una regla de negocio o un umbral evalúa verdadera su condición; nunca por predicción.", "No es producto de inteligencia artificial `[DC-07]`.", "", "Modelado", "Nuevo (Fase 4)", "Evento de dominio; Regla de negocio; Alerta", "EV-INV-006 Existencia mínima alcanzada", True)
T("Acción", "Intención de un actor (solicitar, escanear, consultar, aprobar) que el sistema evalúa; si se acepta, produce uno o más eventos; si no, puede producir un evento de rechazo.", "No es un hecho consumado.", "", "Modelado", "Nuevo (Fase 4)", "Evento de dominio")
T("Registro", "Constancia persistente de un hecho: línea de kardex, registro de bitácora u observación.", "No es sinónimo de «movimiento» (SPEC §0.5).", "", "Modelado", "Nuevo (Fase 4)", "Kardex; Bitácora de auditoría")
T("Hallazgo del dominio", "Inconsistencia o vacío detectado al modelar entre la monografía, el SPEC, el SRS o el Prompt, registrado sin corregirse en silencio (HD-nn).", "—", "", "Modelado", "Nuevo (Fase 4)", "Decisión constitucional")
T("Decisión constitucional", "Determinación del Director, inmodificable dentro del proyecto (DC-01…DC-08).", "—", "", "Proyecto", "SPEC · §0.1", "MVP; Rol; Inteligente")

# ------------------------------------------------------------------ v1.1: cierre del CP-04 (IDs a continuación de GL-203)
T("Primera ubicación", "Movimiento interno que lleva existencia en recepción desde la ubicación de la zona de recepción hasta su ubicación destino, donde queda disponible; queda en el kardex como cualquier movimiento.",
  "No es un cambio de estado sin movimiento, ni una asignación que se registre fuera del kardex.", "asignación de ubicación (como hecho sin movimiento)", "Movimientos", "DF5-03 · RN-MOV-010 · SPEC PN-03", "Movimiento interno; Inventario en recepción; Zona de recepción", "20 metros de L-2026-0142 de la ubicación de recepción R1-01 a Z2-E03-N2", v11=True)
T("Rechazado en sincronización", "Estado final de un registro retenido sin conectividad que, al validarse de nuevo en la sincronización, ya no cumplía las reglas: no se aplicó y conserva su motivo; si describía un hecho físico, abrió una novedad.",
  "No es un movimiento anulado (nunca se confirmó) ni un registro perdido.", "", "Trazabilidad", "DF5-05 · RN-INT-008", "Sincronización; Pendiente de sincronización; Novedad", "Traslado registrado sin conectividad cuya existencia se consumió antes de sincronizar", v11=True)

# ------------------------------------------------------------------ v1.2: decisiones del 30-sep-2026 (IDs a continuación de GL-205)
T("Pieza", "Unidad física individual de mercancía dentro de un lote —rollo, paquete o bolsa, o contenedor agrupado— con cantidad propia registrada en la recepción e identidad interna en el sistema. Pertenece a un solo SKU + Lote y a una sola ubicación; el QR no la identifica: el operario la selecciona tras el escaneo.",
  "No es la unidad de inventario (que es SKU + Lote + Ubicación y agrupa piezas) ni tiene un QR propio.", "", "Inventario y existencia", "Decisiones Q-11, F-1, F-2, F-4, F-6 · SPEC v1.2 · CD-49", "Unidad de inventario; Lote; Rollo; Paquete o bolsa; Contenedor agrupado; Corte parcial", "Un rollo de 40 metros del lote L-2026-0142 en la ubicación A-03", True, v12=True)
T("Rollo", "Tipo de pieza propio de las referencias que se cuentan en metros o kilogramos; tiene cantidad propia y admite cortes parciales.",
  "No es un lote ni una referencia.", "", "Inventario y existencia", "Decisiones F-1, F-3 · SPEC v1.2 · CD-49", "Pieza; Corte parcial; Unidad de medida", "Rollo de tela de 40 m", v12=True)
T("Paquete o bolsa", "Tipo de pieza propio de las referencias que se cuentan en unidades; tiene cantidad propia de unidades.",
  "No es un contenedor agrupado ni una unidad de inventario.", "", "Inventario y existencia", "Decisión F-1 · SPEC v1.2 · CD-49", "Pieza; Contenedor agrupado; Unidad de medida", "Bolsa de 20 camisetas", v12=True)
T("Contenedor agrupado", "Contenedor rotulado que agrupa mercancía sin rotulado individual y se registra como una sola pieza con su cantidad de unidades; pertenece a un solo SKU + Lote (la mezcla de lotes está pendiente, HD-28).",
  "No es una entidad aparte del modelo: es un tipo de pieza.", "", "Inventario y existencia", "Decisión F-6 · SPEC PN-02 E-03 · SPEC v1.2 · CD-49", "Pieza; Paquete o bolsa; Identificador QR", "Caja con prendas sin etiqueta individual", v12=True)
T("Corte parcial", "Salida de una parte de una pieza —por ejemplo, metros cortados de un rollo—: descuenta la cantidad cortada y deja la pieza con su remanente y su identidad. Cumple las reglas de toda salida.",
  "No es un movimiento interno ni una división de la pieza en dos (HD-29).", "", "Salidas", "Decisión F-3 · RN-SAL-008 · SPEC v1.2", "Pieza; Rollo; Salida; Movimiento", "Cortar 6 metros de un rollo de 40 m y dejarlo con 34", v12=True)
