# -*- coding: utf-8 -*-
"""Catálogo de eventos del dominio COLBASOFT — Fase 4."""

EVENTS = []
def E(id, nombre, actor, origen, afect, disp, res, kpi="", rn="", hu="", rf="", crit="Media", reg="Historial", der=None, nota=None):
    sp = lambda s: [x.strip() for x in s.split(",") if x.strip()] if s else []
    EVENTS.append(dict(id=id, nombre=nombre, actor=actor, origen=origen, afect=sp(afect), disp=disp, res=res,
                       kpi=sp(kpi), rn=sp(rn), hu=sp(hu), rf=sp(rf), crit=crit, reg=reg, der=der, nota=nota))

DOMS = [("ACC", "Acceso y sesión", "SD-12"), ("USR", "Usuarios y roles", "SD-12"), ("CAT", "Catálogo", "SD-07"),
        ("BOD", "Estructura de bodega", "SD-06"), ("QRC", "Identificación QR", "SD-08"), ("ENT", "Entradas y recepción", "SD-02"),
        ("LOT", "Lotes", "SD-03"), ("INV", "Inventario y existencia", "SD-01"), ("MOV", "Movimientos internos y transferencias", "SD-02"),
        ("SAL", "Salidas", "SD-02"), ("AJU", "Ajustes", "SD-02"), ("CNT", "Conteos", "SD-04"), ("NOV", "Novedades", "SD-09"),
        ("TRZ", "Trazabilidad y kardex", "SD-03"), ("ALE", "Alertas", "SD-05"), ("REP", "Reportes y exportación", "SD-11"),
        ("AUD", "Auditoría y control", "SD-10"), ("PAR", "Configuración", "SD-13"), ("TAR", "Tareas y notificaciones", "SD-14"),
        ("JOR", "Operación diaria (cierre de jornada)", "SD-15")]

# ---------------------------------------------------------------- ACC
E("EV-ACC-001", "Sesión iniciada", "Cualquier usuario", "E-19", "E-20", "Credenciales individuales válidas de un usuario activo", "Sesión abierta a nombre del usuario; vista según su rol", rn="RN-INT-001", hu="HU-ACC-001", rf="RF-ACC-001, RF-ACC-003", crit="Alta", reg="Bitácora")
E("EV-ACC-002", "Acceso rechazado", "Cualquier persona", "E-19", "E-19", "Credenciales inválidas", "Sin sesión; mensaje que no revela qué dato falló; intento contabilizado", rn="RN-INT-001", hu="HU-ACC-001", rf="RF-ACC-003", crit="Alta", reg="Bitácora")
E("EV-ACC-003", "Cuenta bloqueada", "Sistema", "E-19", "E-19", "Intentos fallidos consecutivos alcanzan el número configurado", "Usuario Bloqueado; Administrador notificado", hu="HU-ACC-001", rf="RF-ACC-004", crit="Alta", reg="Bitácora", der="Umbral configurable de intentos fallidos (RF-ACC-004)")
E("EV-ACC-004", "Sesión cerrada por inactividad", "Sistema", "E-20", "E-20", "Inactividad igual al tiempo configurado, tras aviso previo", "Sesión cerrada; el registro en curso no confirmado se conserva", rn="RN-INT-001", hu="HU-ACC-002", rf="RF-ACC-005", crit="Media", reg="Bitácora", der="Plazo de inactividad configurado (RF-ACC-005)")
E("EV-ACC-005", "Sesión cerrada por el usuario", "Cualquier usuario", "E-20", "E-20", "El usuario cierra su sesión", "Sesión cerrada", hu="HU-ACC-002", rf="RF-ACC-005", crit="Baja", reg="Bitácora")
E("EV-ACC-006", "Contraseña cambiada", "Cualquier usuario", "E-19", "E-19, E-20", "El usuario presenta la actual y una nueva que cumple la política", "Nueva credencial vigente; demás sesiones cerradas; sin registrar valores", hu="HU-ACC-003", rf="RF-ACC-006", crit="Alta", reg="Bitácora")
E("EV-ACC-007", "Acceso restablecido", "Administrador", "E-19", "E-19", "El Administrador desbloquea una cuenta", "Usuario Activo con cambio de contraseña forzado; usuario notificado", hu="HU-ACC-004", rf="RF-ACC-007", crit="Alta", reg="Bitácora")
# ---------------------------------------------------------------- USR
E("EV-USR-001", "Usuario creado", "Administrador", "E-19", "E-19", "Alta de una persona con uno de los cinco roles", "Usuario Activo con rol y ámbito; cambio de contraseña en primer acceso", rn="RN-INT-001, RN-MAE-006", hu="HU-USR-001", rf="RF-USR-001, RF-USR-002, RF-USR-003", crit="Alta", reg="Bitácora")
E("EV-USR-002", "Rol cambiado", "Administrador", "E-19", "E-19", "Cambio de responsabilidades de un usuario", "Nuevo rol vigente desde la siguiente sesión; movimientos anteriores conservan el rol de su momento", rn="RN-MAE-004", hu="HU-USR-003", rf="RF-USR-006, RF-USR-008", crit="Crítica", reg="Bitácora")
E("EV-USR-003", "Ámbito asignado", "Administrador", "E-19", "E-19", "Asignación de bodega y zonas", "Consultas y tareas filtradas por el nuevo ámbito", hu="HU-USR-004", rf="RF-USR-007", crit="Media", reg="Bitácora")
E("EV-USR-004", "Usuario desactivado", "Administrador", "E-19", "E-19, E-20", "La persona deja de operar", "Acceso cerrado de inmediato; historia conservada con su identidad", rn="RN-MAE-004, RN-MAE-007", hu="HU-USR-002", rf="RF-USR-004, RF-USR-005, RF-USR-008", crit="Alta", reg="Bitácora")
E("EV-USR-005", "Usuario reactivado", "Administrador", "E-19", "E-19", "La persona vuelve a operar", "Usuario Activo con su rol", rn="RN-MAE-009", hu="HU-USR-002", rf="RF-USR-004, RF-USR-008", crit="Alta", reg="Bitácora")
E("EV-USR-006", "Retiro del último Administrador o Jefe rechazado", "Sistema", "E-19", "E-19", "Intento de desactivar o cambiar de rol al último Administrador activo o al último Jefe de una bodega", "Operación rechazada con explicación", rn="RN-MAE-004", hu="HU-USR-005, HU-USR-003", rf="RF-USR-006", crit="Alta", reg="Bitácora", der="RN-MAE-004")
# ---------------------------------------------------------------- CAT
E("EV-CAT-001", "Referencia creada", "Administrador / Jefe", "E-01", "E-01", "Alta de una referencia con código, descripción, categoría, tallas y colores", "Referencia Activa", rn="RN-MAE-001", hu="HU-CAT-001", rf="RF-CAT-001, RF-CAT-002, RF-CAT-003", crit="Alta", reg="Bitácora")
E("EV-CAT-002", "SKU generados", "Sistema", "E-01", "E-02", "Referencia creada o ampliada en tallas o colores", "Un SKU por cada combinación talla × color", rn="RN-LOT-002", hu="HU-CAT-001", rf="RF-CAT-004", crit="Media", reg="Historial", der="Regla de composición del SKU (CD-05)")
E("EV-CAT-003", "Unidad de medida asignada", "Administrador / Jefe", "E-01", "E-01", "Definición de la unidad de medida de la referencia", "Todas sus cantidades se expresan en esa unidad", rn="RN-MAE-002, RN-INT-007", hu="HU-CAT-002", rf="RF-CAT-005", crit="Alta", reg="Bitácora")
E("EV-CAT-004", "Umbrales de existencia definidos", "Administrador / Jefe", "E-02", "E-02", "Definición de existencia mínima y máxima de un SKU", "El SKU queda sujeto a alertas de mínimo y máximo", kpi="KPI-19, KPI-21", rn="RN-AUD-004", hu="HU-CAT-004", rf="RF-CAT-007, RF-CAT-008", crit="Media", reg="Bitácora")
E("EV-CAT-005", "Referencia desactivada", "Administrador / Jefe", "E-01", "E-01", "Referencia descontinuada con existencia cero", "No aparece en operaciones nuevas; historia consultable", rn="RN-MAE-003, RN-MAE-007, RN-MAE-008", hu="HU-CAT-003", rf="RF-CAT-006", crit="Alta", reg="Bitácora")
E("EV-CAT-006", "Referencia reactivada", "Administrador / Jefe", "E-01", "E-01", "Referencia vuelve a usarse", "Referencia Activa", rn="RN-MAE-009", hu="HU-CAT-003", rf="RF-CAT-006", crit="Alta", reg="Bitácora")
E("EV-CAT-007", "Catálogo cargado masivamente", "Administrador", "E-01", "E-01, E-02", "Carga de un archivo tabular validado", "Referencias válidas creadas (o ninguna, según la opción); errores por línea reportados", rn="RN-MAE-001", hu="HU-CAT-005", rf="RF-CAT-009", crit="Alta", reg="Bitácora")
E("EV-CAT-008", "Categoría registrada", "Administrador / Jefe", "E-03", "E-03", "Alta o modificación de una categoría y su zona preferente", "Categoría Activa disponible para agrupar referencias", rn="RN-MOV-001", hu="HU-CAT-006", rf="RF-CAT-010", crit="Media", reg="Bitácora")
E("EV-CAT-009", "Categoría desactivada", "Administrador / Jefe", "E-03", "E-03", "Categoría en desuso", "No se asigna a referencias nuevas; historia consultable", rn="RN-MAE-007, RN-MAE-008", hu="HU-CAT-006", rf="RF-CAT-010", crit="Media", reg="Bitácora")
# ---------------------------------------------------------------- BOD
E("EV-BOD-001", "Bodega creada", "Administrador", "E-05", "E-05", "Alta del ámbito físico mayor", "Bodega disponible para zonas", rn="RN-EXI-002", hu="HU-BOD-001", rf="RF-BOD-001", crit="Alta", reg="Bitácora")
E("EV-BOD-002", "Zona creada", "Administrador", "E-05", "E-06", "Alta de una zona con tipo asignado", "Zona disponible para ubicaciones; la bodega cumple la exigencia de zona de recepción", rn="RN-EXI-002", hu="HU-BOD-001", rf="RF-BOD-001, RF-BOD-003", crit="Alta", reg="Bitácora")
E("EV-BOD-003", "Ubicación creada", "Administrador", "E-05", "E-07", "Alta de una ubicación dentro de una zona", "Ubicación Activa; su QR se genera", rn="RN-MAE-006", hu="HU-BOD-001", rf="RF-BOD-001, RF-BOD-002", crit="Alta", reg="Bitácora")
E("EV-BOD-004", "Capacidad de ubicación definida", "Administrador", "E-07", "E-07", "Definición de la capacidad", "La propuesta de destinos y la alerta de sobreocupación usan la capacidad", kpi="KPI-18", rn="RN-MOV-002", hu="HU-BOD-002", rf="RF-BOD-005", crit="Media", reg="Bitácora")
E("EV-BOD-005", "Ubicación desactivada", "Administrador", "E-07", "E-07", "Ubicación fuera de servicio y sin existencia", "No se propone ni acepta como destino", rn="RN-MAE-005, RN-MAE-007", hu="HU-BOD-003", rf="RF-BOD-006", crit="Alta", reg="Bitácora")
E("EV-BOD-006", "Ubicación reactivada", "Administrador", "E-07", "E-07", "Ubicación vuelve a servicio", "Ubicación Activa", rn="RN-MAE-009", hu="HU-BOD-003", rf="RF-BOD-006", crit="Alta", reg="Bitácora")
E("EV-BOD-007", "Coordinador asignado a zona", "Administrador", "E-06", "E-06, E-19", "Designación del responsable de una zona", "Alertas y tareas de la zona se dirigen a él", rn="RN-ALE-005", hu="HU-BOD-004", rf="RF-BOD-007", crit="Media", reg="Bitácora")
E("EV-BOD-008", "Criterios de asignación configurados", "Administrador", "E-05", "E-05", "Definición de criterios y orden de propuesta de ubicación", "Propuestas futuras siguen los criterios", kpi="KPI-10", rn="RN-MOV-001", hu="HU-BOD-005", rf="RF-BOD-008", crit="Media", reg="Bitácora")
# ---------------------------------------------------------------- QRC
E("EV-QRC-001", "Identificador QR generado", "Sistema / Coordinador", "E-09", "E-09", "SKU + Lote confirmado que requiere identificación (un QR por SKU + Lote, DF5-01)", "Código nunca antes emitido, en estado Generado, listo para imprimir", rn="RN-IDE-002", hu="HU-QRC-001", rf="RF-QRC-001, RF-QRC-002", crit="Alta", reg="Historial")
E("EV-QRC-002", "Identificador QR impreso", "Coordinador", "E-09", "E-09", "Impresión individual o por lote de impresión", "Etiqueta física con información legible de respaldo", hu="HU-QRC-001", rf="RF-QRC-005", crit="Baja", reg="Historial")
E("EV-QRC-003", "Identificador QR activado", "Auxiliar", "E-09", "E-09, E-04", "Escaneo de verificación tras adherir la etiqueta", "Identificador Activo; el SKU + Lote queda identificable en cualquier ubicación donde esté (DF5-01)", rn="RN-IDE-001", hu="HU-QRC-002", rf="RF-QRC-003", crit="Media", reg="Historial")
E("EV-QRC-004", "Identificador QR reimpreso", "Coordinador / Auxiliar", "E-09", "E-09", "Reimpresión por deterioro o ilegibilidad, con motivo `[Q-09]`", "Otra copia del mismo QR: el identificador no cambia de identidad ni de estado; la reimpresión queda en el historial", rn="RN-IDE-004, RN-IDE-002", hu="HU-QRC-004", rf="RF-QRC-006, RF-QRC-007", crit="Alta", reg="Bitácora")
E("EV-QRC-005", "Identificador QR anulado", "Coordinador", "E-09", "E-09", "El identificador deja de tener efecto", "Estado Anulado; su código jamás se reemite; su escaneo se rechaza", rn="RN-IDE-002", hu="HU-QRC-002", rf="RF-QRC-002, RF-QRC-007", crit="Alta", reg="Bitácora")
E("EV-QRC-006", "Identificador secundario asociado", "Coordinador", "E-09", "E-09", "Asociación del código de barras del proveedor", "Código de barras habilitado solo para consulta", rn="RN-IDE-003", hu="HU-QRC-005", rf="RF-QRC-008", crit="Media", reg="Historial")
E("EV-QRC-007", "QR de ubicación generado", "Sistema / Administrador", "E-07", "E-09", "Ubicación creada o impresión por zona", "Identificador de ubicación distinguible del de mercancía", rn="RN-IDE-002", hu="HU-QRC-003, HU-BOD-001", rf="RF-QRC-004", crit="Media", reg="Historial")
# ---------------------------------------------------------------- ENT
E("EV-ENT-001", "Documento de entrada creado", "Coordinador", "E-11", "E-11", "Mercancía esperada o recién llegada", "Documento Pendiente de recepción, sin datos comerciales", kpi="KPI-12", rn="RN-ENT-001", hu="HU-ENT-001, HU-ENT-007", rf="RF-ENT-001, RF-ENT-002, RF-ENT-003", crit="Media", reg="Historial")
E("EV-ENT-002", "Posible duplicado advertido", "Sistema", "E-11", "E-11", "Otro documento con igual origen, referencia y fecha", "Advertencia que exige confirmación explícita; no bloquea", rn="RN-ENT-002", hu="HU-ENT-001", rf="RF-ENT-004", crit="Baja", reg="Historial", der="RN-ENT-002")
E("EV-ENT-003", "Recepción física iniciada", "Auxiliar", "E-11", "E-11", "El Auxiliar abre el documento en la tablet", "Recepción en curso atribuida al Auxiliar", kpi="KPI-12", rn="RN-INT-001", hu="HU-ENT-002", rf="RF-ENT-005", crit="Baja", reg="Historial", nota="KPI-12 exige el instante de llegada, que ningún RF captura (PROP-KPI-04 del SRS)")
E("EV-ENT-004", "Línea de recepción registrada", "Auxiliar", "E-11", "E-11", "Conteo físico de una línea recibida", "Cantidad recibida por línea con confirmación visible", rn="RN-INT-003", hu="HU-ENT-002", rf="RF-ENT-005", crit="Media", reg="Historial")
E("EV-ENT-005", "Recepción interrumpida", "Auxiliar", "E-11", "E-11", "Fin de turno o interrupción antes de terminar", "Documento en Recepción parcial", hu="HU-ENT-002", rf="RF-ENT-006", crit="Media", reg="Historial")
E("EV-ENT-006", "Recepción continuada", "Auxiliar", "E-11", "E-11", "Otro usuario retoma una recepción parcial", "Ambos receptores registrados", rn="RN-INT-001", hu="HU-ENT-002", rf="RF-ENT-006", crit="Media", reg="Historial")
E("EV-ENT-007", "Recibido conforme determinado", "Sistema", "E-11", "E-11", "Comparación línea a línea sin diferencias", "Documento Recibido conforme", rn="RN-ENT-003", hu="HU-ENT-004", rf="RF-ENT-007", crit="Media", reg="Historial", der="RN-ENT-003")
E("EV-ENT-008", "Faltante de recepción registrado", "Sistema", "E-11", "E-11", "Recibido < esperado en una línea", "Documento Recibido con novedad; Jefe notificado; no bloquea confirmar lo recibido", rn="RN-ENT-004", hu="HU-ENT-004", rf="RF-ENT-007, RF-ENT-008", crit="Alta", reg="Historial", der="RN-ENT-004")
E("EV-ENT-009", "Sobrante de recepción registrado", "Sistema", "E-11", "E-11", "Recibido > esperado en una línea", "Documento Recibido con novedad; confirmación detenida hasta autorización", rn="RN-ENT-005", hu="HU-ENT-004", rf="RF-ENT-007, RF-ENT-009", crit="Alta", reg="Historial", der="RN-ENT-005")
E("EV-ENT-010", "Sobrante autorizado", "Jefe de Bodega", "E-11", "E-11", "El Jefe acepta el sobrante", "El sobrante puede ingresar al confirmar", rn="RN-ENT-005, RN-AJU-001", hu="HU-ENT-004", rf="RF-ENT-009", crit="Crítica", reg="Bitácora")
E("EV-ENT-011", "Mercancía dañada registrada en recepción", "Auxiliar", "E-11", "E-11, E-08, E-17", "Parte de lo recibido llega dañada", "Cantidad dañada separada; ingresa inmovilizada en cuarentena; novedad abierta; Jefe notificado", kpi="KPI-23", rn="RN-ENT-006", hu="HU-ENT-005", rf="RF-ENT-012", crit="Alta", reg="Historial")
E("EV-ENT-012", "Entrada confirmada", "Coordinador", "E-11", "E-11, E-04, E-08, E-10", "Verificación por una persona distinta de quien recibió", "Lote creado o asociado; movimiento de entrada en el kardex; existencia En recepción en una ubicación de la zona de recepción (RN-EXI-007, DF5-02)", kpi="KPI-05, KPI-11, KPI-12", rn="RN-ENT-007, RN-EXI-007, RN-INT-002, RN-INT-004, RN-INT-003, RN-LOT-001", hu="HU-ENT-003", rf="RF-ENT-010, RF-ENT-011, RF-LOT-001", crit="Alta", reg="Kardex + Bitácora")
E("EV-ENT-013", "Retorno registrado como entrada", "Coordinador", "E-11", "E-11, E-10", "Vuelve mercancía que había salido", "Entrada nueva que referencia la salida original; la salida no se reversa", rn="RN-SAL-007", hu="HU-SAL-006", rf="RF-SAL-011", crit="Alta", reg="Kardex")
E("EV-ENT-014", "Autoconfirmación de entrada rechazada", "Sistema", "E-11", "E-11", "Quien registró la recepción intenta confirmarla", "Confirmación rechazada; se exige un segundo actor", rn="RN-ENT-007", hu="HU-ENT-003", rf="RF-ENT-010", crit="Alta", reg="Bitácora", der="RN-ENT-007")
E("EV-ENT-015", "Documento de entrada reversado", "Coordinador", "E-11", "E-11", "Documento aún no confirmado que no procede", "Documento Reversado, sin efecto en el inventario", rn="RN-MAE-007", crit="Media", reg="Bitácora", nota="Función de M-07 sin HU ni RF (HD-19)")
E("EV-ENT-016", "Pieza registrada en la recepción", "Auxiliar", "E-11", "E-11, E-27", "Conteo físico de una pieza recibida (rollo, paquete, bolsa o contenedor agrupado) `[Q-11]` `[F-1]` `[F-2]` `[F-6]`", "Pieza con su tipo y su cantidad propia asociada a un SKU + Lote; la cantidad recibida de la línea es la suma de sus piezas; confirmación visible", rn="RN-LOT-006, RN-LOT-007", hu="HU-ENT-009, HU-ENT-010", rf="RF-ENT-014, RF-ENT-015, RF-ENT-016", crit="Alta", reg="Historial")
# ---------------------------------------------------------------- LOT
E("EV-LOT-001", "Lote creado", "Sistema", "E-11", "E-04", "Confirmación de una entrada", "Lote Habilitado con origen y fecha de ingreso, único en su SKU", rn="RN-LOT-001, RN-LOT-002, RN-MAE-006", hu="HU-LOT-001", rf="RF-LOT-001, RF-LOT-002, RF-LOT-003", crit="Alta", reg="Historial")
E("EV-LOT-002", "Lote inmovilizado", "Jefe / Administrador", "E-04", "E-04, E-08", "Sospecha de calidad u origen, con motivo tipificado", "Toda la existencia del lote pasa a Inmovilizado en todas sus ubicaciones", rn="RN-LOT-003, RN-EXI-006", hu="HU-LOT-003, HU-LOT-002, HU-KDX-004", rf="RF-LOT-005", crit="Crítica", reg="Bitácora")
E("EV-LOT-003", "Lote liberado", "Jefe / Administrador", "E-04", "E-04, E-08", "Verificación concluida, con motivo tipificado", "La existencia vuelve a sus estados normales", rn="RN-LOT-004", hu="HU-LOT-003", rf="RF-LOT-005", crit="Crítica", reg="Bitácora")
E("EV-LOT-004", "Antigüedad de lote superada", "Sistema", "E-04", "E-18", "Días en bodega sobre el umbral configurado", "Lote destacado; alerta informativa al Jefe", kpi="KPI-17", rn="RN-LOT-005", hu="HU-LOT-004", rf="RF-LOT-006", crit="Baja", reg="Historial", der="RN-LOT-005")
# ---------------------------------------------------------------- INV
E("EV-INV-001", "Mercancía ubicada", "Auxiliar", "E-10", "E-10, E-08, E-07", "Escaneo de la mercancía en recepción y de la ubicación destino", "Movimiento interno de primera ubicación confirmado: la cantidad sale de la unidad de la ubicación de recepción y entra Disponible a la unidad destino; existencia total invariante; kardex con qué, cuánto, origen, destino, quién, cuándo y documento de entrada; confirmación visible", kpi="KPI-05, KPI-10, KPI-18", rn="RN-MOV-010, RN-MOV-004, RN-EXI-002, RN-MOV-002, RN-MOV-001, RN-MOV-011", hu="HU-ENT-006, HU-MOV-008", rf="RF-BOD-004, RF-BOD-005, RF-MOV-001, RF-MOV-002, RF-MOV-005, RF-MOV-012", crit="Alta", reg="Kardex")
E("EV-INV-002", "Desviación de ubicación registrada", "Sistema", "E-08", "E-08", "Mercancía ubicada en un lugar distinto al propuesto", "Desviación registrada como información (no falta); Coordinador notificado", kpi="KPI-10", rn="RN-MOV-003", hu="HU-ENT-006", crit="Baja", reg="Historial", der="RN-MOV-003", nota="Sin RF que la implemente (H-11 del SRS)")
E("EV-INV-003", "Existencia reservada", "Sistema", "E-08", "E-08", "Salida autorizada o transferencia creada", "Porción Disponible → Reservado; ninguna otra operación puede comprometerla", rn="RN-EXI-004, RN-EXI-003", hu="HU-SAL-002, HU-MOV-003", rf="RF-SAL-005, RF-MOV-007", crit="Media", reg="Historial")
E("EV-INV-004", "Reserva liberada", "Sistema", "E-08", "E-08", "Cancelación de la salida o de la transferencia antes del despacho", "Porción Reservado → Disponible", rn="RN-EXI-004, RN-MOV-009", hu="HU-SAL-002, HU-MOV-007", rf="RF-SAL-009, RF-MOV-011", crit="Media", reg="Historial")
E("EV-INV-005", "Reserva vencida liberada", "Sistema", "E-12", "E-08, E-12", "Salida autorizada no ejecutada dentro del plazo", "Reserva liberada; solicitud Vencida; alerta al solicitante", rn="RN-SAL-005", hu="HU-SAL-002", crit="Media", reg="Historial", der="RN-SAL-005", nota="Sin RF que la implemente (H-11 del SRS)")
E("EV-INV-006", "Existencia mínima alcanzada", "Sistema", "E-02", "E-18", "Existencia disponible del SKU por debajo de su mínimo", "Condición de ruptura inminente vigente; genera una sola alerta", kpi="KPI-19, KPI-21", rn="RN-ALE-001, RN-ALE-005", hu="HU-ALE-001", rf="RF-ALE-001, RF-ALE-004", crit="Media", reg="Historial", der="Umbral mínimo por SKU (RF-CAT-007) + RN-ALE-001")
E("EV-INV-007", "Existencia máxima superada", "Sistema", "E-02", "E-18", "Existencia del SKU por encima de su máximo", "Condición de sobre stock vigente; alimenta la rotación", kpi="KPI-16, KPI-19", rn="RN-ALE-001", hu="HU-ALE-002", rf="RF-ALE-001, RF-ALE-004", crit="Media", reg="Historial", der="Umbral máximo por SKU (RF-CAT-007) + RN-ALE-001")
E("EV-INV-008", "Existencia en cero alcanzada", "Sistema", "E-02", "E-18", "Una referencia activa queda sin existencia", "Evento de ruptura contabilizado; alerta de existencia en cero", kpi="KPI-21, KPI-19", rn="RN-ALE-001", hu="HU-ALE-001", rf="RF-ALE-004", crit="Media", reg="Historial", der="Tipo de alerta «existencia en cero» (RF-ALE-004)")
E("EV-INV-009", "Ubicación sobreocupada", "Sistema", "E-07", "E-18", "La ocupación de una ubicación supera su capacidad", "Alerta de sobreocupación al Coordinador de la zona", kpi="KPI-18, KPI-19", rn="RN-MOV-002, RN-ALE-001", hu="HU-BOD-002", rf="RF-BOD-005, RF-ALE-004", crit="Media", reg="Historial", der="RN-MOV-002", nota="Cálculo de ocupación con unidades heterogéneas pendiente (HD-17)")
# ---------------------------------------------------------------- MOV
E("EV-MOV-001", "Movimiento interno confirmado", "Auxiliar", "E-10", "E-08, E-07", "Escaneo de mercancía, selección de la pieza (la ubicación filtra y verifica, F-4), ubicación de origen si hay varias (DF5-01) y ubicación destino; la primera ubicación desde la zona de recepción es EV-INV-001", "Existencia descontada del origen y sumada al destino; total invariante; kardex actualizado", kpi="KPI-05, KPI-11", rn="RN-MOV-004, RN-MOV-005, RN-INT-002, RN-EXI-003, RN-MOV-011", hu="HU-MOV-001, HU-MOV-008", rf="RF-MOV-001, RF-MOV-002, RF-MOV-012", crit="Alta", reg="Kardex")
E("EV-MOV-002", "Movimiento interno rechazado", "Sistema", "E-10", "E-08", "Cantidad mayor a la disponible, destino igual al origen, destino inactivo o sin capacidad, o existencia inmovilizada", "Operación rechazada con explicación comprensible", rn="RN-EXI-003, RN-MOV-005, RN-MOV-002, RN-EXI-006", hu="HU-MOV-002", rf="RF-MOV-003, RF-MOV-004, RF-MOV-005, RF-MOV-006", crit="Media", reg="Bitácora", der="RN-EXI-003, RN-MOV-005, RN-MOV-002, RN-EXI-006")
E("EV-MOV-003", "Movimiento interno interrumpido", "Auxiliar / Sistema", "E-10", "E-08", "El traslado se inicia y no se cierra (también el de primera ubicación)", "Porción En tránsito: no disponible en origen ni destino", rn="RN-MOV-006, RN-EXI-005", crit="Media", reg="Historial", nota="Sin HU ni RF (H-11 del SRS)")
E("EV-MOV-004", "Tránsito interno prolongado detectado", "Sistema", "E-10", "E-18", "Movimiento interno en tránsito supera el tiempo máximo", "Alerta de tránsito prolongado", rn="RN-MOV-006", rf="RF-ALE-004", crit="Media", reg="Historial", der="RN-MOV-006", nota="Sin HU (H-11 del SRS)")
E("EV-MOV-005", "Transferencia creada", "Coordinador", "E-13", "E-13, E-08", "Necesidad de mover existencia entre zonas o bodegas", "Transferencia Pendiente de despacho; reserva en origen; tarea al Auxiliar del origen", rn="RN-EXI-003, RN-EXI-004", hu="HU-MOV-003", rf="RF-MOV-007", crit="Media", reg="Historial")
E("EV-MOV-006", "Despacho de transferencia confirmado", "Auxiliar (origen)", "E-13", "E-13, E-08", "Escaneo de la mercancía despachada", "Transferencia En tránsito; porción Reservado → En tránsito", kpi="KPI-15", rn="RN-EXI-005", hu="HU-MOV-004", rf="RF-MOV-008, RF-MOV-009", crit="Alta", reg="Kardex")
E("EV-MOV-007", "Transferencia completada", "Auxiliar (destino)", "E-13", "E-13, E-08, E-10", "Recepción escaneada igual a lo despachado", "Existencia descontada del origen y sumada al destino; ambos movimientos en el kardex", kpi="KPI-15, KPI-11, KPI-05", rn="RN-MOV-007, RN-INT-002", hu="HU-MOV-004", rf="RF-MOV-008, RF-MOV-010", crit="Alta", reg="Kardex")
E("EV-MOV-008", "Diferencia de transferencia registrada", "Sistema", "E-13", "E-13, E-17", "Recibido < despachado", "Transferencia Con diferencia; novedad abierta; resolución del Jefe requerida", kpi="KPI-23", rn="RN-MOV-007", hu="HU-MOV-005", rf="RF-MOV-010", crit="Alta", reg="Historial", der="RN-MOV-007")
E("EV-MOV-009", "Recepción de transferencia rechazada por exceso", "Sistema", "E-13", "E-13", "Recibido > despachado", "Recepción rechazada; escalamiento al Jefe", rn="RN-MOV-007", hu="HU-MOV-005", rf="RF-MOV-010", crit="Alta", reg="Bitácora", der="RN-MOV-007")
E("EV-MOV-010", "Diferencia de transferencia resuelta", "Jefe de Bodega", "E-13", "E-13", "El Jefe investiga y resuelve", "Transferencia Completada; resolución documentada", rn="RN-MOV-007", hu="HU-MOV-005", rf="RF-MOV-010", crit="Alta", reg="Bitácora")
E("EV-MOV-011", "Tiempo máximo en tránsito excedido", "Sistema", "E-13", "E-18", "Transferencia en tránsito más allá del plazo", "Alerta al Jefe con contenido y responsable de despacho", kpi="KPI-15, KPI-19", rn="RN-MOV-008", hu="HU-MOV-006", rf="RF-MOV-011", crit="Media", reg="Historial", der="RN-MOV-008")
E("EV-MOV-012", "Transferencia cancelada antes del despacho", "Coordinador", "E-13", "E-13, E-08", "La transferencia ya no procede", "Transferencia Cancelada con motivo; reserva liberada", rn="RN-MOV-009", hu="HU-MOV-007", rf="RF-MOV-011", crit="Alta", reg="Bitácora")
E("EV-MOV-013", "Transferencia cancelada en tránsito", "Jefe de Bodega", "E-13", "E-13, E-08, E-10", "La mercancía no puede llegar a destino", "Transferencia Cancelada con motivo; movimiento de retorno al origen", rn="RN-MOV-009", hu="HU-MOV-007", rf="RF-MOV-011", crit="Crítica", reg="Kardex + Bitácora")
# ---------------------------------------------------------------- SAL
E("EV-SAL-001", "Salida solicitada", "Jefe / Coordinador", "E-12", "E-12", "Requerimiento de mercancía (consumo, despacho, devolución, baja)", "Solicitud con motivo tipificado, sin datos comerciales; disponibilidad verificada", rn="RN-SAL-002, RN-EXI-003", hu="HU-SAL-001", rf="RF-SAL-001, RF-SAL-002, RF-SAL-003", crit="Media", reg="Historial")
E("EV-SAL-002", "Salida rechazada por existencia insuficiente", "Sistema", "E-12", "E-12", "Cantidad solicitada mayor que la disponible", "Rechazo con la cantidad disponible; ofrecimiento de salida parcial", rn="RN-EXI-001, RN-EXI-003", hu="HU-SAL-004", rf="RF-SAL-004", crit="Media", reg="Bitácora", der="RN-EXI-001")
E("EV-SAL-003", "Salida autorizada", "Jefe / Coordinador", "E-12", "E-12, E-08, E-23", "Aprobación de la solicitud por quien corresponde", "Solicitud Autorizada; existencia reservada; tarea de preparación generada", kpi="KPI-22", rn="RN-SAL-001, RN-AJU-001, RN-EXI-004, RN-SAL-003", hu="HU-SAL-002, HU-SAL-007", rf="RF-SAL-005, RF-SAL-006, RF-SAL-007", crit="Crítica", reg="Bitácora")
E("EV-SAL-004", "Salida escalada al Jefe", "Sistema", "E-12", "E-12", "Solicitud sobre el umbral del Coordinador", "Autorización enrutada al Jefe", rn="RN-SAL-001", hu="HU-SAL-007", rf="RF-SAL-006", crit="Media", reg="Historial", der="RN-SAL-001")
E("EV-SAL-005", "Escaneo de preparación rechazado", "Sistema", "E-12", "E-12", "Unidad escaneada distinta de la solicitada", "Rechazo con la discrepancia concreta (referencia, talla, color o lote)", rn="RN-SAL-004", hu="HU-SAL-003", rf="RF-SAL-008", crit="Media", reg="Historial", der="RN-SAL-004")
E("EV-SAL-006", "Salida ejecutada", "Auxiliar", "E-12", "E-12, E-08, E-10", "Preparación completa confirmada", "Movimiento de salida en el kardex; existencia descontada; reserva liberada", kpi="KPI-05, KPI-11, KPI-16", rn="RN-EXI-001, RN-INT-002, RN-INT-004", hu="HU-SAL-003", rf="RF-SAL-009", crit="Alta", reg="Kardex")
E("EV-SAL-007", "Salida parcial autorizada", "Jefe de Bodega", "E-12", "E-12, E-08", "Disponible insuficiente y se acepta retirar lo que hay", "Solicitud ajustada a la cantidad disponible", kpi="KPI-22", rn="RN-EXI-001, RN-AJU-001", hu="HU-SAL-004", rf="RF-SAL-004", crit="Alta", reg="Bitácora")
E("EV-SAL-008", "Baja por daño aprobada", "Jefe de Bodega", "E-12", "E-12, E-08, E-10", "Solicitud de baja con motivo específico, observación y evidencia", "Movimiento de salida marcado como baja; alimenta el reporte de mermas", kpi="KPI-13", rn="RN-SAL-006, RN-AJU-001", hu="HU-SAL-005", rf="RF-SAL-010", crit="Crítica", reg="Kardex + Bitácora")
E("EV-SAL-009", "Salida rechazada por el autorizador", "Jefe / Coordinador", "E-12", "E-12", "El autorizador no aprueba la solicitud", "Solicitud Rechazada; solicitante notificado", kpi="KPI-22", rn="RN-AJU-001", hu="HU-TAR-002", crit="Alta", reg="Bitácora", nota="Función de M-08 sin RF propio")
E("EV-SAL-010", "Preparación de salida iniciada", "Auxiliar", "E-12", "E-12", "Primer escaneo válido de la tarea de preparación", "Solicitud En preparación; progreso visible", rn="RN-SAL-003, RN-SAL-004", hu="HU-SAL-003", rf="RF-SAL-007, RF-SAL-008", crit="Baja", reg="Historial")
E("EV-SAL-011", "Salida cancelada", "Jefe / Coordinador", "E-12", "E-12, E-08", "La salida autorizada ya no procede", "Solicitud Cancelada; reserva liberada", rn="RN-EXI-004", hu="HU-SAL-002", crit="Alta", reg="Bitácora", nota="Actor y RF no definidos en el SPEC (HD-19)")
E("EV-SAL-012", "Pieza tomada en la preparación", "Auxiliar", "E-12", "E-12, E-27", "Escaneo del SKU + Lote y selección de la pieza que se toma `[Q-10]` `[F-4]`", "La pieza se cuenta una sola vez en la preparación; el progreso muestra piezas y cantidad tomadas frente a lo solicitado", rn="RN-SAL-009, RN-MOV-011", hu="HU-SAL-008", rf="RF-SAL-012", crit="Media", reg="Historial")
E("EV-SAL-013", "Corte parcial registrado", "Auxiliar", "E-12", "E-12, E-27, E-10", "Corte de parte de un rollo durante una salida `[F-3]`", "Cantidad cortada descontada de la pieza, que conserva su identidad y su remanente; salida con motivo tipificado, autorización y atribución personal", rn="RN-SAL-008, RN-LOT-007", hu="HU-SAL-009", rf="RF-SAL-013", crit="Alta", reg="Kardex")
# ---------------------------------------------------------------- AJU
E("EV-AJU-001", "Ajuste solicitado", "Coordinador", "E-14", "E-14", "Diferencia entre existencia registrada y física (hallazgo, conteo o novedad)", "Solicitud Pendiente de aprobación con motivo y evidencia; existencia sin cambios", kpi="KPI-14", rn="RN-AJU-003, RN-EXI-001", hu="HU-AJU-001", rf="RF-AJU-001, RF-AJU-002, RF-AJU-003", crit="Alta", reg="Bitácora")
E("EV-AJU-002", "Ajuste clasificado y enrutado", "Sistema", "E-14", "E-14", "Solicitud recibida", "Clasificación menor/mayor con umbral aplicado; enrutamiento al Jefe o al Administrador", rn="RN-AJU-002, RN-EXI-006", hu="HU-AJU-003", rf="RF-AJU-004", crit="Media", reg="Historial", der="RN-AJU-002")
E("EV-AJU-003", "Ajuste escalado por autoaprobación", "Sistema", "E-14", "E-14", "El aprobador designado es el solicitante", "Solicitud Escalada al nivel superior", rn="RN-AJU-001", hu="HU-AJU-002", rf="RF-AJU-005", crit="Crítica", reg="Bitácora", der="RN-AJU-001")
E("EV-AJU-004", "Ajuste aprobado", "Jefe / Administrador", "E-14", "E-14", "Revisión de unidad, diferencia, motivo, solicitante y evidencia", "Solicitud Aprobada; se origina el movimiento de ajuste", kpi="KPI-14, KPI-22", rn="RN-AJU-001, RN-EXI-001", hu="HU-AJU-002, HU-AJU-003", rf="RF-AJU-005, RF-AJU-007", crit="Crítica", reg="Bitácora")
E("EV-AJU-005", "Ajuste aplicado", "Sistema", "E-14", "E-10, E-08", "Aprobación de la solicitud", "Movimiento de ajuste en el kardex; existencia corregida; unidad marcada como ajustada", kpi="KPI-08, KPI-14", rn="RN-INT-004, RN-AJU-007, RN-EXI-001", hu="HU-AJU-002", rf="RF-AJU-007", crit="Crítica", reg="Kardex")
E("EV-AJU-006", "Ajuste rechazado", "Jefe / Administrador", "E-14", "E-14", "El aprobador no acepta la solicitud", "Solicitud Rechazada con justificación; solicitante notificado; existencia sin cambios", kpi="KPI-22", rn="RN-AJU-006", hu="HU-AJU-002", rf="RF-AJU-008", crit="Crítica", reg="Bitácora")
E("EV-AJU-007", "Ajuste negativo impedido", "Sistema", "E-14", "E-14", "El ajuste dejaría existencia negativa", "Rechazo sin excepción; explicación de existencia y diferencia", rn="RN-EXI-001", hu="HU-AJU-004", rf="RF-AJU-006", crit="Crítica", reg="Bitácora", der="RN-EXI-001")
E("EV-AJU-008", "Solicitud de ajuste vencida escalada", "Sistema", "E-14", "E-14, E-18", "Solicitud sin resolver más allá del plazo", "Escalamiento al nivel superior y alerta", kpi="KPI-22", rn="RN-AJU-005", hu="HU-TAR-002", rf="RF-ALE-004", crit="Alta", reg="Bitácora", der="RN-AJU-005")
E("EV-AJU-009", "Patrón de ajustes recurrentes detectado", "Sistema", "E-14", "E-18", "Ajustes sobre una misma unidad superan el umbral en la ventana", "Alerta al Jefe y al Auditor con ajustes, solicitantes y aprobadores", kpi="KPI-14, KPI-19", rn="RN-AJU-004", hu="HU-AJU-005", rf="RF-AJU-009", crit="Crítica", reg="Bitácora", der="RN-AJU-004")
E("EV-AJU-010", "Solicitud bloqueada sin aprobador", "Sistema", "E-14", "E-14", "No existe nivel superior disponible", "Solicitud Bloqueada; Administrador notificado", rn="RN-AJU-001", hu="HU-AJU-002", rf="RF-AJU-005", crit="Crítica", reg="Bitácora", der="RN-AJU-001")
# ---------------------------------------------------------------- CNT
E("EV-CNT-001", "Conteo cíclico programado", "Coordinador", "E-15", "E-15", "Programación periódica, alerta de exactitud o decisión del Coordinador", "Conteo Programado con alcance; no bloquea la bodega", kpi="KPI-03", hu="HU-CNT-001", rf="RF-CNT-001, RF-CNT-002", crit="Media", reg="Historial")
E("EV-CNT-002", "Conteo general programado", "Jefe de Bodega", "E-15", "E-15", "Cierre de período o exigencia de auditoría", "Conteo Programado con fecha de corte; usuarios notificados con anticipación", kpi="KPI-02", rn="RN-CNT-006", hu="HU-CNT-006", rf="RF-CNT-011", crit="Alta", reg="Bitácora")
E("EV-CNT-003", "Existencia teórica congelada", "Sistema", "E-15", "E-15", "Inicio del conteo", "Fotografía inmutable del ámbito; conteo En ejecución", rn="RN-CNT-001", hu="HU-CNT-001, HU-CNT-003", rf="RF-CNT-003, RF-CNT-004", crit="Alta", reg="Historial")
E("EV-CNT-004", "Movimientos bloqueados por conteo general", "Sistema", "E-15", "E-10", "Llegada de la fecha de corte", "Registro de movimientos bloqueado en la bodega", rn="RN-CNT-006", hu="HU-CNT-006", rf="RF-CNT-011", crit="Crítica", reg="Bitácora", der="RN-CNT-006")
E("EV-CNT-005", "Movimiento de excepción autorizado", "Jefe de Bodega", "E-15", "E-10", "Necesidad urgente durante el bloqueo", "Movimiento permitido y marcado como excepción en el kardex", rn="RN-CNT-006", hu="HU-CNT-006", rf="RF-CNT-011", crit="Crítica", reg="Kardex + Bitácora")
E("EV-CNT-006", "Tarea de conteo asignada", "Sistema / Coordinador", "E-15", "E-16", "Generación de tareas del ámbito", "Tarea Asignada a un contador identificado", rn="RN-CNT-003", hu="HU-CNT-001", rf="RF-CNT-005", crit="Baja", reg="Historial")
E("EV-CNT-007", "Conteo físico registrado", "Auxiliar", "E-16", "E-16", "Escaneo de ubicación y registro de la cantidad de cada pieza contada a mano `[F-5]`", "Existencia contada guardada pieza por pieza sin mostrar la esperada; tarea Confirmada", kpi="KPI-03", rn="RN-CNT-002, RN-CNT-009", hu="HU-CNT-002, HU-CNT-010", rf="RF-CNT-006, RF-CNT-014", crit="Media", reg="Historial")
E("EV-CNT-008", "Línea de conteo clasificada", "Sistema", "E-15", "E-15", "Comparación de lo contado con la existencia congelada", "Línea Conforme, Sobrante o Faltante; conteo En conciliación", kpi="KPI-01, KPI-04, KPI-08", rn="RN-CNT-001", hu="HU-CNT-003", rf="RF-CNT-007", crit="Media", reg="Historial", der="Regla de clasificación (CD-27)")
E("EV-CNT-009", "Segundo conteo requerido", "Sistema", "E-15", "E-16", "Diferencia de una línea sobre la tolerancia", "Tarea de segundo conteo para una persona distinta", kpi="KPI-06", rn="RN-CNT-003", hu="HU-CNT-004", rf="RF-CNT-008, RF-CNT-009", crit="Media", reg="Historial", der="RN-CNT-003")
E("EV-CNT-010", "Diferencia persistente escalada", "Sistema", "E-15", "E-15", "El segundo conteo también difiere", "Escalamiento al Jefe para verificación presencial", rn="RN-CNT-003", hu="HU-CNT-004", rf="RF-CNT-008", crit="Alta", reg="Historial", der="RN-CNT-003")
E("EV-CNT-011", "Tarea de conteo reasignada", "Coordinador", "E-16", "E-16", "El contador asignado no está disponible", "Nuevo contador; ambos registrados; conteo parcial conservado", rn="RN-CNT-003", hu="HU-CNT-009", rf="RF-TAR-004", crit="Media", reg="Historial")
E("EV-CNT-012", "Ubicación excluida del conteo general", "Jefe de Bodega", "E-15", "E-15", "Ubicación imposible de cubrir", "Exclusión con justificación; cobertura documentada", kpi="KPI-03", rn="RN-CNT-007", hu="HU-CNT-007", rf="RF-CNT-012", crit="Alta", reg="Bitácora")
E("EV-CNT-013", "Diferencia global crítica detectada", "Sistema", "E-15", "E-15", "Diferencia global del conteo general sobre el umbral crítico", "Administrador y Auditor notificados antes de permitir el cierre", kpi="KPI-02", rn="RN-CNT-008", crit="Crítica", reg="Bitácora", der="RN-CNT-008", nota="Sin HU ni RF (H-11 del SRS)")
E("EV-CNT-014", "Conteo cerrado", "Jefe de Bodega", "E-15", "E-15, E-14", "Revisión del consolidado de diferencias", "Conteo Cerrado (no se reabre); ajustes derivados solicitados; en el general, fin del bloqueo", kpi="KPI-01, KPI-02", rn="RN-CNT-004, RN-CNT-003, RN-CNT-007, RN-AJU-001", hu="HU-CNT-005, HU-CNT-007", rf="RF-CNT-010, RF-CNT-012", crit="Crítica", reg="Bitácora")
E("EV-CNT-015", "Exactitud del inventario calculada", "Sistema", "E-15", "E-15", "Cierre del conteo", "Exactitud del ámbito almacenada históricamente (KPI-01; KPI-02 en el general)", kpi="KPI-01, KPI-02, KPI-03, KPI-04", rn="RN-CNT-004", hu="HU-CNT-008", rf="RF-CNT-013, RF-REP-003", crit="Alta", reg="Historial", der="Fórmula de KPI-01")
E("EV-CNT-016", "Movimientos desbloqueados", "Sistema", "E-15", "E-10", "Cierre o aborto del conteo general", "Registro de movimientos habilitado", rn="RN-CNT-006", hu="HU-CNT-006", rf="RF-CNT-011", crit="Alta", reg="Bitácora", der="RN-CNT-006")
E("EV-CNT-017", "Conteo abortado", "Jefe de Bodega", "E-15", "E-15", "El conteo no puede completarse", "Congelamiento liberado; conteos parciales conservados sin ajustes", crit="Alta", reg="Bitácora", nota="PN-09 E-04; función de M-11 sin HU ni RF propios")
E("EV-CNT-018", "Conteo vencido", "Sistema", "E-15", "E-15, E-18", "Conteo no ejecutado o no cerrado en el plazo", "Alerta; si excede el máximo, congelamiento liberado y conteo Vencido", rn="RN-CNT-005", rf="RF-ALE-004", crit="Media", reg="Historial", der="RN-CNT-005", nota="Sin HU propia")
# ---------------------------------------------------------------- NOV
E("EV-NOV-001", "Novedad reportada", "Auxiliar (o rol operativo) · Sistema, al rechazar un registro sincronizado", "E-17", "E-17", "Hallazgo físico: dañada, sin identificador, en ubicación incorrecta o inexistente; o registro rechazado al sincronizar que describe un hecho físico ya realizado (EV-TRZ-007)", "Novedad Abierta dirigida al Coordinador de la zona, sin imputación al reportante", kpi="KPI-23", rn="RN-NOV-003, RN-INT-008", hu="HU-NOV-001", rf="RF-NOV-001, RF-NOV-002, RF-NOV-003, RF-NOV-004", crit="Media", reg="Historial")
E("EV-NOV-002", "Novedad vinculada a novedad abierta", "Sistema", "E-17", "E-17", "Reporte sobre una unidad que ya tiene novedad abierta", "Se vincula; no se duplica", rn="RN-NOV-003", hu="HU-NOV-002", rf="RF-NOV-005", crit="Baja", reg="Historial", der="RN-NOV-003")
E("EV-NOV-003", "Acción de novedad determinada", "Coordinador", "E-17", "E-17", "Evaluación de la novedad", "Acción: ajuste, reidentificación, reubicación o baja", hu="HU-NOV-002", rf="RF-NOV-004", crit="Media", reg="Historial")
E("EV-NOV-004", "Novedad resuelta y cerrada", "Coordinador / Jefe", "E-17", "E-17", "El movimiento de resolución se confirma", "Novedad Cerrada resuelta, vinculada a su resolución", kpi="KPI-23", rn="RN-MAE-007", hu="HU-NOV-002", rf="RF-NOV-006", crit="Media", reg="Historial")
E("EV-NOV-005", "Novedad cerrada como improcedente", "Coordinador / Jefe", "E-17", "E-17", "La novedad se reportó por error", "Novedad Cerrada improcedente con justificación; no se elimina", kpi="KPI-23", rn="RN-MAE-007", hu="HU-NOV-002", rf="RF-NOV-006", crit="Media", reg="Historial")
E("EV-NOV-006", "Novedad escalada por vencimiento", "Sistema", "E-17", "E-17, E-18", "Novedad sin resolver más allá del plazo", "Novedad Escalada al Jefe; alerta", kpi="KPI-23", rn="RN-NOV-002", hu="HU-NOV-003", rf="RF-ALE-007", crit="Media", reg="Historial", der="RN-NOV-002", nota="Cobertura RF parcial (H-11, H-13 del SRS)")
E("EV-NOV-007", "Mercancía sin registro incorporada", "Coordinador / Jefe", "E-17", "E-08, E-14, E-09", "Identificación de mercancía encontrada sin registro", "Unidad creada o seleccionada, ajuste por sobrante aprobado por el Jefe, QR y ubicación asignados", rn="RN-NOV-001, RN-AJU-003", hu="HU-NOV-004", rf="RF-AJU-001, RF-AJU-002, RF-QRC-001, RF-BOD-004", crit="Crítica", reg="Kardex + Bitácora", nota="Cobertura RF parcial (H-13 del SRS)")
# ---------------------------------------------------------------- TRZ
E("EV-TRZ-001", "Movimiento confirmado en el kardex", "Usuario / Sistema", "E-10", "E-08", "Cualquier movimiento satisface sus reglas y se confirma", "Línea inmutable con fecha, hora, tipo, cantidad, existencia resultante, ubicación, usuario, motivo y documento", kpi="KPI-05, KPI-11, KPI-17, KPI-24", rn="RN-INT-001, RN-INT-002, RN-INT-004, RN-LOT-007", hu="HU-KDX-001, HU-KDX-006", rf="RF-KDX-001, RF-KDX-002, RF-KDX-003, RF-KDX-008", crit="Alta", reg="Kardex")
E("EV-TRZ-002", "Movimiento anulado", "Jefe / Administrador", "E-10", "E-10, E-08", "Error detectado en un movimiento confirmado", "Movimiento inverso con motivo y autorización; ambos visibles", kpi="KPI-08", rn="RN-INT-002", hu="HU-KDX-002", rf="RF-KDX-004", crit="Crítica", reg="Kardex + Bitácora")
E("EV-TRZ-003", "Registro retenido sin conectividad", "Sistema", "E-10", "E-10", "Pérdida de conectividad durante un registro", "Registro Pendiente de sincronización; no confirma documentos", rn="RN-INT-003", hu="HU-ENT-002", rf="RF-ENT-005", crit="Media", reg="Historial", der="RN-INT-003")
E("EV-TRZ-004", "Registro sincronizado", "Sistema", "E-10", "E-10", "Conectividad restablecida y el registro sigue cumpliendo las reglas frente al estado vigente", "Registro validado de nuevo (RN-INT-008) y Confirmado con su fecha operativa original (HD-16)", rn="RN-INT-003, RN-INT-008", hu="HU-ENT-002", rf="RF-ENT-005", crit="Media", reg="Historial", der="RN-INT-003, RN-INT-008")
E("EV-TRZ-005", "Verificación de integridad ejecutada", "Auditor", "E-08", "E-08", "Solicitud de verificación por unidad, lote o global", "Resultado exportable de la comparación existencia vs. suma de movimientos", kpi="KPI-09", rn="RN-AUD-005, RN-INT-004", hu="HU-KDX-003", rf="RF-KDX-006", crit="Alta", reg="Bitácora")
E("EV-TRZ-007", "Registro rechazado al sincronizar", "Sistema", "E-10", "E-10, E-17", "Al sincronizar, el registro retenido ya no cumple alguna regla o invariante frente al estado vigente", "Registro Rechazado en sincronización, sin efecto en la existencia; constancia del registro original, su autor, el motivo y el instante; si describe un hecho físico, abre una novedad (EV-NOV-001)", rn="RN-INT-008", hu="HU-ENT-002", rf="RF-ENT-005", crit="Alta", reg="Bitácora", der="RN-INT-008", nota="Nuevo en la v1.1 (DF5-05, HD-24). Ningún RF describe todavía el rechazo; se apoya en RF-ENT-005 y RNF-DSP-002")
E("EV-TRZ-006", "Discrepancia de integridad detectada", "Sistema", "E-08", "E-08", "Existencia ≠ suma de movimientos (unidad, lote o global)", "Hallazgo crítico notificado al Administrador", kpi="KPI-09", rn="RN-INT-004", hu="HU-KDX-003", rf="RF-KDX-006, RF-AUD-007", crit="Crítica", reg="Bitácora", der="RN-INT-004")
# ---------------------------------------------------------------- ALE
E("EV-ALE-001", "Alerta generada", "Sistema", "E-18", "E-18", "Una condición de regla se cumple (eventos EV-INV-006…009, EV-MOV-004, EV-MOV-011, EV-AJU-008, EV-AJU-009, EV-CNT-018, EV-LOT-004, EV-ALE-007)", "Alerta Activa con tipo, severidad y destinatario por rol; una sola por condición", kpi="KPI-19", rn="RN-ALE-001, RN-ALE-005", hu="HU-ALE-001, HU-ALE-002", rf="RF-ALE-001, RF-ALE-002, RF-ALE-003, RF-ALE-004", crit="Media", reg="Historial", der="RN-ALE-001")
E("EV-ALE-002", "Alerta atendida", "Jefe / Coordinador", "E-18", "E-18", "El destinatario ejecuta la acción correctiva", "Alerta Atendida con quién, cuándo y qué se hizo", kpi="KPI-19, KPI-20", hu="HU-ALE-003", rf="RF-ALE-005", crit="Media", reg="Historial")
E("EV-ALE-003", "Alerta descartada", "Jefe / Coordinador", "E-18", "E-18", "El destinatario considera que no requiere acción", "Alerta Descartada con motivo obligatorio", kpi="KPI-19", rn="RN-ALE-004", hu="HU-ALE-003", rf="RF-ALE-005", crit="Alta", reg="Bitácora")
E("EV-ALE-004", "Alerta escalada", "Sistema", "E-18", "E-18", "Alerta crítica sin atención dentro del plazo", "Alerta Escalada al rol superior con notificación adicional", kpi="KPI-20", rn="RN-ALE-002", hu="HU-ALE-004", rf="RF-ALE-007", crit="Alta", reg="Bitácora", der="RN-ALE-002")
E("EV-ALE-005", "Alerta cerrada automáticamente", "Sistema", "E-18", "E-18", "La condición de disparo deja de cumplirse", "Alerta Cerrada sin atención si nadie actuó", kpi="KPI-19", rn="RN-ALE-003", hu="HU-ALE-001", rf="RF-ALE-007", crit="Baja", reg="Historial", der="RN-ALE-003")
E("EV-ALE-006", "Frecuencia anómala de disparo reportada", "Sistema", "E-18", "E-25", "Un tipo de alerta se dispara con frecuencia anómala", "Reporte al Administrador para recalibrar umbrales", kpi="KPI-19", rn="RN-ALE-001", hu="HU-ALE-005", rf="RF-ALE-006", crit="Baja", reg="Historial", der="PN-11 E-04")
E("EV-ALE-007", "Exactitud bajo el umbral detectada", "Sistema", "E-15", "E-18", "Exactitud calculada inferior al umbral configurado (no es meta: DEC/línea base)", "Alerta de exactitud por debajo del objetivo", kpi="KPI-01", rn="RN-ALE-001", rf="RF-ALE-004", crit="Media", reg="Historial", der="Tipo de alerta «exactitud por debajo del objetivo» (RF-ALE-004)", nota="Sin HU propia")
# ---------------------------------------------------------------- REP
E("EV-REP-001", "Datos exportados", "Jefe / Administrador / Auditor / Coordinador", "E-21", "E-21", "Exportación de un reporte, del kardex o de la bitácora", "Exportación registrada con usuario, alcance y fecha, respetando la visibilidad por rol", rn="RN-AUD-003", hu="HU-REP-002, HU-REP-003, HU-ENT-008, HU-AJU-006", rf="RF-REP-006", crit="Alta", reg="Bitácora")
E("EV-REP-002", "Exportación analítica habilitada", "Administrador", "E-25", "E-25", "Decisión de alimentar la herramienta analítica externa", "Datos expuestos de forma estructurada `[DC-06]`", rn="RN-AUD-004", hu="HU-REP-003", rf="RF-REP-004, RF-REP-005", crit="Crítica", reg="Bitácora")
E("EV-REP-003", "Reporte programado", "Jefe de Bodega", "E-25", "E-25", "Definición de reporte, periodicidad y destinatarios", "Programación vigente (puede desactivarse)", hu="HU-REP-004", rf="RF-REP-007", crit="Media", reg="Bitácora")
E("EV-REP-004", "Reporte programado generado", "Sistema", "E-25", "E-25", "Llega la periodicidad programada", "Reporte con fecha, hora y generador, puesto a disposición", hu="HU-REP-004", rf="RF-REP-002, RF-REP-007", crit="Baja", reg="Historial", der="Periodicidad programada (RF-REP-007)")
E("EV-REP-005", "Indicadores del período calculados", "Sistema", "E-15", "E-25", "Cierre del período de cada KPI (diario, semanal, mensual)", "Los 24 KPI calculados sobre el registro del sistema", kpi="KPI-02, KPI-03, KPI-04, KPI-05, KPI-06, KPI-07, KPI-08, KPI-09, KPI-10, KPI-11, KPI-12, KPI-13, KPI-14, KPI-15, KPI-16, KPI-17, KPI-18, KPI-19, KPI-20, KPI-21, KPI-22, KPI-23, KPI-24", hu="HU-CNT-008", rf="RF-REP-003", crit="Baja", reg="Historial", der="Frecuencia de cada KPI (SPEC Cap. 10)")
# ---------------------------------------------------------------- AUD
E("EV-AUD-001", "Observación de auditoría registrada", "Auditor", "E-22", "E-22", "Hallazgo o comentario del Auditor", "Observación Abierta en registro separado; el inventario no cambia", rn="RN-AUD-002", hu="HU-AUD-003", rf="RF-AUD-006", crit="Alta", reg="Bitácora")
E("EV-AUD-002", "Observación de auditoría cerrada", "Por definir (DEC-04)", "E-22", "E-22", "Respuesta a la observación", "Observación Cerrada con respuesta; no se elimina", rn="RN-AUD-002, RN-MAE-007", hu="HU-AUD-003", rf="RF-AUD-006", crit="Alta", reg="Bitácora", nota="Actor que responde no definido (DEC-04)")
E("EV-AUD-003", "Intento de escritura del Auditor rechazado", "Sistema", "E-19", "E-21", "El Auditor intenta cualquier escritura sobre el inventario", "Rechazo sin excepción y registro del intento", rn="RN-AUD-002", hu="HU-AUD-002", rf="RF-AUD-005", crit="Crítica", reg="Bitácora", der="RN-AUD-002 / PR-02")
E("EV-AUD-004", "Operación no autorizada rechazada", "Sistema", "E-19", "E-21", "Cualquier rol intenta una operación fuera de sus permisos", "Rechazo con usuario, operación y fecha (RNF-SEG-007)", rn="RN-INT-001", hu="HU-PAR-003", crit="Alta", reg="Bitácora", der="Matriz de segregación §2.7", nota="Respaldado por RNF-SEG-003, RNF-SEG-004, RNF-SEG-007")
E("EV-AUD-005", "Aprobación propia detectada", "Sistema", "E-21", "E-21", "Verificación encuentra solicitante = aprobador en ajuste, salida o conteo", "Hallazgo crítico: la regla debió impedirlo", kpi="KPI-14", rn="RN-AJU-001", hu="HU-AUD-004", rf="RF-AUD-007", crit="Crítica", reg="Bitácora", der="RN-AJU-001")
E("EV-AUD-006", "Discontinuidad de bitácora detectada", "Sistema", "E-21", "E-21", "Falta un eslabón en la secuencia de la bitácora", "Hallazgo crítico de integridad", rn="RN-AUD-001", hu="HU-AUD-001", rf="RF-AUD-007", crit="Crítica", reg="Bitácora", der="RN-AUD-001")
# ---------------------------------------------------------------- PAR
E("EV-PAR-001", "Parámetro modificado", "Administrador", "E-25", "E-25", "Cambio de un umbral, plazo o política dentro de su rango", "Nuevo valor vigente hacia adelante; valor anterior y nuevo en bitácora", rn="RN-AUD-004, RN-AJU-002, RN-SAL-001, RN-MOV-008, RN-CNT-003", hu="HU-PAR-001", rf="RF-PAR-001, RF-PAR-002, RF-PAR-003, RF-PAR-004", crit="Crítica", reg="Bitácora")
E("EV-PAR-002", "Motivo tipificado creado", "Administrador", "E-24", "E-24", "Nueva causa para un tipo de operación", "Motivo Activo, con indicación de si exige evidencia", rn="RN-AJU-003", hu="HU-PAR-002", rf="RF-PAR-005", crit="Alta", reg="Bitácora")
E("EV-PAR-003", "Motivo tipificado desactivado", "Administrador", "E-24", "E-24", "Motivo en desuso", "Motivo Inactivo: fuera de operaciones nuevas, visible en el histórico", rn="RN-MAE-007, RN-MAE-008", hu="HU-PAR-002", rf="RF-PAR-005", crit="Alta", reg="Bitácora")
E("EV-PAR-004", "Configuración de regla estructural rechazada", "Sistema", "E-25", "E-25", "Intento de parametrizar o eludir una regla estructural", "Rechazo y registro del intento", rn="RN-INT-002, RN-EXI-001, RN-AJU-001", hu="HU-PAR-003", rf="RF-PAR-006", crit="Crítica", reg="Bitácora", der="RF-PAR-006 / IN-67")
E("EV-PAR-005", "Motivo tipificado reactivado", "Administrador", "E-24", "E-24", "Motivo vuelve a usarse", "Motivo Activo", rn="RN-MAE-009", hu="HU-PAR-002", rf="RF-PAR-005", crit="Alta", reg="Bitácora")
# ---------------------------------------------------------------- TAR
E("EV-TAR-001", "Tarea generada", "Sistema", "E-23", "E-23", "Asignación de trabajo de recepción, ubicación, preparación o transferencia", "Tarea Pendiente en el panel del responsable (qué, dónde, cuánto)", rn="RN-INT-001", hu="HU-TAR-001", rf="RF-TAR-001, RF-TAR-002", crit="Baja", reg="Historial")
E("EV-TAR-002", "Tarea completada", "Sistema", "E-23", "E-23", "Confirmación del hecho asociado", "Tarea Completada; no se cierra por declaración", hu="HU-TAR-001, HU-DSH-002", rf="RF-TAR-003", crit="Baja", reg="Historial", der="IN-69")
E("EV-TAR-003", "Tarea reasignada", "Coordinador", "E-23", "E-23", "Equilibrio de carga o ausencia", "Nuevo responsable notificado; ambos registrados", rn="RN-CNT-003", hu="HU-TAR-003, HU-DSH-003", rf="RF-TAR-004", crit="Media", reg="Historial")
E("EV-TAR-004", "Solicitud de aprobación notificada", "Sistema", "E-14", "E-19", "Solicitud de ajuste o salida pendiente para un aprobador", "Solicitud visible en el panel del aprobador, ordenada por antigüedad y monto", kpi="KPI-22", hu="HU-TAR-002", rf="RF-AJU-004", crit="Baja", reg="Historial")
E("EV-TAR-005", "Resultado notificado al solicitante", "Sistema", "E-14", "E-19", "Resolución de una solicitud", "El solicitante conoce el resultado", hu="HU-TAR-002, HU-AJU-002", rf="RF-AJU-008", crit="Baja", reg="Historial")
E("EV-TAR-006", "Tarea cancelada", "Sistema", "E-23", "E-23", "La operación de origen se cancela o vence", "Tarea Cancelada", crit="Baja", reg="Historial", der="Cancelación o vencimiento del origen", nota="Estado nuevo (HD-19)")
# ---------------------------------------------------------------- JOR
E("EV-JOR-001", "Pendientes de jornada consolidados", "Sistema", "E-26", "E-26", "Fin de jornada o de turno", "Lista de recepciones sin confirmar, tránsitos, conteos abiertos, ajustes sin resolver, novedades y alertas", rn="RN-MOV-006", crit="Media", reg="Historial", der="PN-14", nota="⚠️ Sin HU ni RF (DEC-05)")
E("EV-JOR-002", "Pendientes traspasados", "Coordinador", "E-26", "E-26, E-23", "Revisión de pendientes no resueltos en el turno", "Responsabilidad de los pendientes traspasada explícitamente", crit="Media", reg="Bitácora", nota="⚠️ Sin HU ni RF (DEC-05)")
E("EV-JOR-003", "Jornada cerrada", "Jefe / Coordinador", "E-26", "E-26", "Resumen revisado y sin registros pendientes de sincronización", "Cierre registrado con quién lo ejecutó", rn="RN-INT-003", crit="Alta", reg="Bitácora", nota="⚠️ Sin HU ni RF (DEC-05)")
E("EV-JOR-004", "Cierre de jornada bloqueado", "Sistema", "E-26", "E-26", "Existen registros sin sincronizar", "Cierre impedido hasta sincronizar (RNF-DSP-003)", rn="RN-INT-003", crit="Alta", reg="Bitácora", der="RN-INT-003", nota="⚠️ Sin HU ni RF (DEC-05)")
E("EV-JOR-005", "Cierre de jornada omitido", "Sistema", "E-26", "E-26, E-18", "Termina la jornada sin cierre", "Omisión registrada; alerta al Jefe al día siguiente", crit="Media", reg="Bitácora", der="PN-14 E-03", nota="⚠️ Sin HU ni RF (DEC-05)")

# ================================================================== LÍNEAS TEMPORALES
TIMELINES = [
 ("PN-01", "Recepción de mercancía", "CU-06", [
   ("EV-ENT-001", "El Coordinador crea el documento"), ("EV-ENT-002", "si hay posible duplicado"), ("EV-TAR-001", "tarea de recepción"),
   ("EV-ENT-003", ""), ("EV-ENT-004", "una vez por línea"), ("EV-ENT-016", "por cada pieza de la línea"), ("EV-TRZ-003", "si se pierde la conectividad"), ("EV-TRZ-004", "al restablecerse, si sigue siendo válido"), ("EV-TRZ-007", "si al sincronizar ya no es válido → EV-NOV-001 si describe un hecho físico"),
   ("EV-ENT-005", "si se interrumpe"), ("EV-ENT-006", "si otro usuario la continúa"), ("EV-ENT-011", "si llega mercancía dañada → abre EV-NOV-001"),
   ("EV-ENT-007 | EV-ENT-008 | EV-ENT-009", "según la comparación"), ("EV-ENT-010", "solo si hubo sobrante"), ("EV-ENT-014", "si el receptor intenta confirmar"),
   ("EV-ENT-012", "confirmación por una segunda persona"), ("EV-LOT-001", ""), ("EV-TRZ-001", "movimiento de entrada"), ("EV-TAR-002", "tarea de recepción completada")]),
 ("PN-02", "Registro inicial e identificación", "CU-07", [
   ("EV-QRC-001", ""), ("EV-QRC-002", ""), ("EV-QRC-003", "tras adherir y escanear"), ("EV-QRC-004", "si la impresión sale ilegible"), ("EV-QRC-006", "si viene código de barras del proveedor")]),
 ("PN-03", "Ubicación física de mercancía", "CU-08", [
   ("EV-TAR-001", "tarea de ubicación con propuesta"), ("EV-MOV-003", "si el traslado se interrumpe"), ("EV-INV-001", "movimiento interno de primera ubicación (DF5-03)"), ("EV-INV-002", "si ubica en otro lugar"),
   ("EV-INV-009", "si se excede la capacidad"), ("EV-TRZ-001", ""), ("EV-TAR-002", "")]),
 ("PN-04", "Consulta de existencia y ubicación", "CU-09", [
   ("—", "La consulta no produce eventos: leer nunca escribe (RN-INT-006). Solo si el identificador no se reconoce puede seguir EV-NOV-001.")]),
 ("PN-05", "Movimiento interno (reubicación)", "CU-10", [
   ("EV-MOV-002", "si alguna regla lo impide (fin)"), ("EV-MOV-003", "si se interrumpe"), ("EV-MOV-004", "si el tránsito se prolonga"),
   ("EV-TRZ-003", "si se pierde la conectividad"), ("EV-TRZ-004 | EV-TRZ-007", "al sincronizar: confirmado o rechazado (→ EV-NOV-001)"),
   ("EV-MOV-001", "confirmación"), ("EV-TRZ-001", "")]),
 ("PN-06", "Transferencia entre zonas o bodegas", "CU-11", [
   ("EV-MOV-005", ""), ("EV-INV-003", ""), ("EV-TAR-001", "tarea de despacho"), ("EV-MOV-012", "si se cancela antes del despacho → EV-INV-004 (fin)"),
   ("EV-MOV-006", ""), ("EV-MOV-011", "si se excede el tiempo en tránsito"), ("EV-MOV-013", "si el Jefe la cancela en tránsito (fin)"),
   ("EV-MOV-007", "si lo recibido coincide"), ("EV-MOV-008 | EV-MOV-009", "si no coincide"), ("EV-MOV-010", "resolución del Jefe"), ("EV-TRZ-001", "movimientos de despacho y recepción")]),
 ("PN-07", "Ajuste de inventario", "CU-12", [
   ("EV-AJU-001", ""), ("EV-AJU-007", "si dejaría existencia negativa (fin)"), ("EV-AJU-002", ""), ("EV-TAR-004", ""),
   ("EV-AJU-003", "si aprobador = solicitante"), ("EV-AJU-010", "si no hay nivel superior"), ("EV-AJU-008", "si vence el plazo"),
   ("EV-AJU-004 | EV-AJU-006", "decisión"), ("EV-AJU-005", "solo si fue aprobado"), ("EV-TRZ-001", ""), ("EV-TAR-005", ""), ("EV-AJU-009", "si se acumulan ajustes sobre la misma unidad")]),
 ("PN-08", "Conteo cíclico", "CU-13", [
   ("EV-CNT-001", ""), ("EV-CNT-003", ""), ("EV-CNT-006", "una por contador"), ("EV-CNT-011", "si un contador no está"),
   ("EV-CNT-007", "sin ver lo esperado"), ("EV-CNT-008", ""), ("EV-CNT-009", "si la diferencia supera la tolerancia"), ("EV-CNT-010", "si el segundo también difiere"),
   ("EV-NOV-001", "si aparece mercancía sin identificador"), ("EV-CNT-018", "si vence el plazo"), ("EV-CNT-014", "cierre por el Jefe"),
   ("EV-AJU-001", "por cada línea que el Jefe decide ajustar → PN-07"), ("EV-CNT-015", ""), ("EV-ALE-007", "si la exactitud queda bajo el umbral")]),
 ("PN-09", "Conteo general", "CU-14", [
   ("EV-CNT-002", ""), ("EV-CNT-004", "al llegar el corte"), ("EV-CNT-003", ""), ("EV-CNT-006", "cubriendo todas las ubicaciones"),
   ("EV-CNT-005", "si urge un movimiento de excepción"), ("EV-CNT-007", ""), ("EV-CNT-008", ""), ("EV-CNT-009", ""), ("EV-CNT-012", "si una ubicación se excluye"),
   ("EV-CNT-013", "si la diferencia global es crítica"), ("EV-CNT-017", "si se aborta (→ EV-CNT-016, fin)"), ("EV-CNT-014", ""), ("EV-AJU-001", "ajustes derivados → PN-07"),
   ("EV-CNT-016", ""), ("EV-CNT-015", "KPI-01 y KPI-02")]),
 ("PN-10", "Salida de mercancía", "CU-15", [
   ("EV-SAL-001", ""), ("EV-SAL-002", "si no hay disponible suficiente"), ("EV-SAL-004", "si supera el umbral del Coordinador"), ("EV-TAR-004", ""),
   ("EV-SAL-003 | EV-SAL-009", "decisión"), ("EV-SAL-007", "salida parcial autorizada"), ("EV-INV-003", ""), ("EV-TAR-001", "tarea de preparación"),
   ("EV-SAL-010", ""), ("EV-SAL-012", "por cada pieza tomada"), ("EV-SAL-013", "si se corta parte de un rollo"), ("EV-SAL-005", "por cada escaneo incorrecto"), ("EV-INV-005", "si la reserva vence (fin)"), ("EV-SAL-011", "si se cancela (fin)"),
   ("EV-SAL-006", ""), ("EV-SAL-008", "si el motivo es baja por daño"), ("EV-TRZ-001", ""), ("EV-TAR-002", ""), ("EV-INV-006 | EV-INV-008", "si la salida deja el SKU bajo el mínimo o en cero")]),
 ("PN-11", "Gestión de alerta operativa", "CU-16", [
   ("EV-INV-006 … EV-INV-009 · EV-MOV-004 · EV-MOV-011 · EV-AJU-008 · EV-AJU-009 · EV-CNT-018 · EV-LOT-004 · EV-ALE-007", "condición detectada"),
   ("EV-ALE-001", ""), ("EV-ALE-004", "si es crítica y vence el plazo"), ("EV-ALE-002 | EV-ALE-003 | EV-ALE-005", "desenlace"), ("EV-ALE-006", "si el tipo se dispara con frecuencia anómala")]),
 ("PN-12", "Reporte de novedad de mercancía", "CU-17", [
   ("EV-NOV-001 | EV-NOV-002", "nueva o vinculada"), ("EV-NOV-006", "si vence el plazo"), ("EV-NOV-003", ""),
   ("EV-AJU-001", "si implica ajuste → PN-07"), ("EV-NOV-007", "si es mercancía sin registro"), ("EV-NOV-004 | EV-NOV-005", "cierre")]),
 ("PN-13", "Auditoría de inventario", "CU-18", [
   ("EV-TRZ-005", ""), ("EV-TRZ-006", "si hay discrepancia"), ("EV-AUD-005", "si hay aprobación propia"), ("EV-AUD-006", "si la bitácora tiene discontinuidad"),
   ("EV-AUD-003", "si el Auditor intenta escribir"), ("EV-AUD-001", ""), ("EV-REP-001", "exportación del reporte de auditoría"), ("EV-AUD-002", "al responderse la observación")]),
 ("PN-14", "Cierre operativo de jornada ⚠️", "CU-19", [
   ("EV-JOR-001", ""), ("EV-JOR-004", "si hay registros sin sincronizar"), ("EV-JOR-002", ""), ("EV-JOR-003", ""), ("EV-JOR-005", "si nadie cierra")]),
]
